### ISSUE TITLE
Landesverbände

### ISSUE THREAD

**Issue by mschunk** [leichtathletik/dlv-datenaustausch#1]
Für Landesverbände werden drei Informationen geführt:
StateID
StateCode
StateCodeNumeric

Beispiel:
StateID = 01
StateCode = BA 
StateCodeNumeric = 1

Die Informationen sind redundand und unnötig kompliziert. Vorschlag der Vereinfachung: StateID und StateCodeNumeric entfernen - es wird nur StateCode verwendet.

**Comment by mschunk** [comment]
Alle anwesenden stimmen der Änderung zu.

**Comment by UdoLaubDLV** [comment]
In die Dokumentation so aufgenommen.

**Comment by mschunk** [comment]
Für Württemberg wird nun der Code `WU` verwendet (`Club.xsd`).
LADV verwendet in seinen Datenformaten für Württemberg den Code `WÜ`.
Alle anderen Landesverbands Codes sind identisch.

Vorschlag in den DLV Datenformaten Württemberg auf `WÜ` ändern. Dann wären die Landesverbandscodes in allen Datenformaten einheitlich.

**Comment by UdoLaubDLV** [comment]
Ich habe gesehen, dass auch Cosa und TAF3 „WÜ“ nutzen.

Ich würde deshalb, wenn es keine Widersprüche gibt, das XSD ändern.

Beim Austausch mit DLV-net müsste man dann auf WU ändern.

**Comment by mschunk** [comment]
in Club.xsd vom 16.10.2019 umgesetzt.
