### ISSUE TITLE
"Brauche ich das noch?"

### ISSUE THREAD

**Issue by mschunk** [leichtathletik/dlv-datenaustausch#10]
Es wäre Wünschenswert wenn die Informationen soweit vereinfacht werden können, dass keine XML Datei dafür mehr notwendig ist, sondern diese "statischen Daten" als Anlage zur Dokumentation bereitgestellt werden.

**Comment by mschunk** [comment]
AgeGroups und States werden nicht mehr benötigt. Sind über Dokumentation festgelegt. 

Kreise und Bezirke werden ggf. benötigt. Keine Entscheidung. Ggf. in Clubs-Datei aufnehmen.

**Comment by UdoLaubDLV** [comment]
Offen was mit Kreisen und Bezirken passiert. Alles andere aus der Dokumentation entfernt.

**Comment by mschunk** [comment]
siehe: https://github.com/leichtathletik/dlv-datenaustausch/issues/21
