### ISSUE TITLE
Schnittstellendokumentation aktuell?

### ISSUE THREAD

**Issue by mschunk** [leichtathletik/dlv-datenaustausch#12]
Dirk Wagner hat während der Telefonkonferenz am 25.06.2010 erwähnt das er sich bzl. des Stammdatenaustausches noch in Feinabstimmung befindet. Solche Abstimmungen sind üblicherweise dann notwendig wenn Dokumentation unvollständig und/oder nicht eindeutig ist.

Sind alle neuen Erkenntnisse aus der Feinabstimmung Wagner/Sonstige in die Dokumentation eingeflossen? Laut Dokumentation `Stand: 05.03.2018` ist dem nicht so. Bis wann wird eine aktuelle Dokumentation vorliegen?

**Comment by UdoLaubDLV** [comment]
Dokumentation ist aktuell.
