### ISSUE TITLE
Element License

### ISSUE THREAD

**Issue by mschunk** [leichtathletik/dlv-datenaustausch#14]
Über das Element `License` können Lizenzinformationen in die Zukunft und in die Vergangenheit weitergegeben werden. Es existiert keine Vorgabe für welchen Zeitraum die Daten bereitgestellt werden.

Die Dokumentation sollte hier eine eindeutige Aussage machen, da sonst ein Abgleich der Informationen nicht möglich ist.

**Comment by UdoLaubDLV** [comment]
full = aktuelles Jahr plus Änderungen Folgejahr
