### ISSUE TITLE
PersonID kann Null sein

### ISSUE THREAD

**Issue by mschunk** [leichtathletik/dlv-datenaustausch#17]
Laut Dokumentation darf PersonID im Element Person Null sein. Wie soll dies zukünftig funktionieren?
Was passiert mit `PersonCodeOld` ?

**Comment by mschunk** [comment]
Gleiches vorgehen wie bei VereinIDs:
Mastersystem legt die PersonID fest. Es soll eine Guid (Class 4) verwendet werden. Bei der Datenmenge an Personen sollte es eigentlich keine Kollisionen geben. Wenn ja, muss manuell eingegriffen werden. Feld wird required.
PersonCodeOld wird gestrichen.

Die StartrechtNummer wird über das Lizenz Element weitergegeben.

**Comment by mschunk** [comment]
Für Vereinswechsel könnte in Zukunft vom abgebenden System die GUID mit an das aufnehmende Mastersystem kommuniziert werden. Eindeutige Zuordnung des Athleten. Guid wird nur einmal beim anlegen vergeben.

**Comment by UdoLaubDLV** [comment]
In die Dokumentation so aufgenommen.
