### ISSUE TITLE
ClubIDDistrictID/CountyID/StateID

### ISSUE THREAD

**Issue by mschunk** [leichtathletik/dlv-datenaustausch#2]
Welche IDs werden zukünftig verwendet? 
Wer vergibt zukünftig IDs?

Vorschlag: Mastersystem vergibt die IDs in einem Vorgegebenen Nuimmernkreis.

**Comment by mschunk** [comment]
## Clubs
Nummern werden weiterhin benötigt.
Nummern werden vom Mastersystem innerhalb eines vorgegebenen Nummernkreises Vergeben
SSXXXXXXXXX

Beispiel:
BAXXXXXXX (Baden: 7 Stellen für LV)

## Kreise / Bezirk
- Nummern werden weiterhin beötigt
- Nummern werden vom Mastersystem innerhalb eines vorgegebenen Nummernkreises Vergeben
- Kreis/bezirk/Vereinsnummern dürfen sich nicht überschneiden

Beispiel:
BAXXXXXXX (Baden: 7 Stellen für LV)

**Comment by UdoLaubDLV** [comment]
In die Dokumentation und XSD so aufgenommen.
