### ISSUE TITLE
Mastersystsemtabelle - ungültige Systemcodes

### ISSUE THREAD

**Issue by mschunk** [leichtathletik/dlv-datenaustausch#20]
Mastersystemtabelle Stand 8.10.2019.

Wir haben bisher über den Stammdatenaustausch zwischen Phoenix II, LADV und la.net 2 gesprochen. Damit ist es nicht möglich das in der Tabelle in einer Zeile mehr als ein System genannt wird oder anderes Systeme auftauchen.

**Comment by UdoLaubDLV** [comment]
Mastersysteme: 
Westfalen = LA.net2
Rheinland = LA.net2 (Udo klärt)
Baden/Brandenburg = LADV

**Comment by mschunk** [comment]
Die Mastersystemtabelle wurde in die Schnittstellenbeschreibung aufgenommen und aktualisiert.
