### ISSUE TITLE
Counties und Districts in Verein XML aufnehmen

### ISSUE THREAD

**Issue by mschunk** [leichtathletik/dlv-datenaustausch#21]
Über die Vereine-XML werden Vereine und deren zuordnungen zu Kreisen und Bezirken (Counties und Districts) ausgetauscht. Es wäre sinnvoll die Kreise und Bezirke auf die referenziert wird auch in dieser Datei zu definieren.

Vorschlag:
```xml
<StateData>
  <Request/>
  <Clubs/>
  <Counties/> <--- NEU
  <Districts/> <--- NEU
</StateData>
```

Dokumentation und XSD wären anzupassen.

**Comment by UdoLaubDLV** [comment]
Wäre für mich ok. Dirk schaut es sich an.
Passen die Attribute gemäß der Dokumentation?

**Comment by diwaffm** [comment]
Ich denke auch, dass das ein gangbarer Weg ist...

**Comment by UdoLaubDLV** [comment]
Sollte die XSD von clubs umbenannt werden?
ClubsCountiesRegions?
Bleibt der Name des Endpunkts bei clubs?

**Comment by mschunk** [comment]
> Sollte die XSD von clubs umbenannt werden?

Der Name kann bleiben wie er ist. Spielt an sich keine Rolle wie der Name der Datei ist.

> Bleibt der Name des Endpunkts bei clubs?

Ja.

**Comment by diwaffm** [comment]
Weil das gerade in der Diskussion aufgekommen ist:
Auch bei den Kreisen und Bezirken wird - wenn vorhanden - die Relation zur übergeordneten Organisation gelistet?
D.h. in einem Verband, der sowohl Kreise als auch Bezirke hat, gibt es dann bei den Kreisen das Feld DistrictId?

**Comment by mschunk** [comment]
in Club.xsd vom 16.10.2019 umgesetzt.
