### ISSUE TITLE
City vs. StrippedName

### ISSUE THREAD

**Issue by mschunk** [leichtathletik/dlv-datenaustausch#24]
In CLUB.xsd hat das Element Club u.A. folgende Attribute:
```
City=""                     String (Teil des Vereinsnamens der den Ort bestimmt)
StrippedName=""                 String
```

Was ist der Unterschied? In allen Beispielen in der Dokumentation ist der Wert identisch.

Wenn es keinen Unterschied gibt sollte ein Attribut entfernt werden.

**Comment by diwaffm** [comment]
City ist der Ort, nachdem die Sortierung des Vereins im Wettkampfprogramm erfolgt,
StrippedName ist eine Kurzfassung des Vereinsnamens, die z.B. bei Staffeln und Teams Verwendung finden kann.

LG Eintracht Frankfurt
City = "Frankfurt"
StrippedName = "LGEF"

TSV Bayer 04 Leverkusen
City = "Leverkusen"
StrippedName = "Bayer Leverkusen"

**Comment by UdoLaubDLV** [comment]
Dann würde ich das Feld belassen.

Wird das auch bei Startgemeinschaften mit ewig langen Namen genutzt...?

**Comment by mschunk** [comment]
@diwaffm Danke - das hat geholfen.

Vorschlag: `StrippedName ` in `ShortName ` umbenannen. Dann hätte ich direkt verstanden was gemeint ist. Zudem versteht man unter "strippedName" wohl etwas anderes. 

Zudem sollten alle XML Beispiele in der Dokumentation korrigiert werden. Diese sind nach der Erklärung von Dirk m.E. alle falsch. Beispiel:
```xml
<Club 
...
Name="SSV Gymnasium Heinzenwies" 
City=" Heinzenwies" 
StrippedName="Heinzenwies" 
```
besser:
```xml
<Club 
...
Name="SSV Gymnasium Heinzenwies" 
City=" Heinzenwies" 
ShortName="SSV Gym. Heinzenwies" 
```

**Comment by mschunk** [comment]
@UdoLaubDLV 

> Wird das auch bei Startgemeinschaften mit ewig langen Namen genutzt...?
In LADV muss der Kurzname für alle Vereine, LGs und STGs gesetzt werden.

**Comment by diwaffm** [comment]
Ob meine oben gepostete "Erklärung" die ist, die die Initiatoren des Formats im Kopf hatten, weiß ich nicht - ich hatte damals geschaut, welche Datenfelder in LA.Net da passen würden und was dort gespeichert wird...

@mschunk 
Ist es absicht, dass vor dem Namen der Stadt ein Blank steht? Das gehört da meiner Meinung nach nicht hin...

**Comment by mschunk** [comment]
@diwaffm 

> Ist es absicht, dass vor dem Namen der Stadt ein Blank steht? Das gehört da meiner Meinung nach nicht hin...

Nein. Copy & Paste Fehler aus dem Word Document. ... fixed.

> Ob meine oben gepostete "Erklärung" die ist, die die Initiatoren des Formats im Kopf hatten, weiß ich nicht - ich hatte damals geschaut, welche Datenfelder in LA.Net da passen würden und was dort gespeichert wird...

Was die "Initiatoren des Formats im Kopf hatten" ist m.E, nicht mehr relevant. Was du schreibst mit "StrippedName ist eine Kurzfassung des Vereinsnamens" halte ich für wichtig und sollten wir genau so machen. Vereinsnamen mit bis z u 200 Zeichen sind an vielen stellen nicht praktikabel. Ein Kurzname des Vereins ist an vielen stellen wichtig (und in LADV vorhanden).
