### ISSUE TITLE
Kreis als Organisation vs. Kreis als Strukturebene

### ISSUE THREAD

**Issue by diwaffm** [leichtathletik/dlv-datenaustausch#25]
In den Testdaten, die ich von Phoenix bekommen habe, befindet sich unter "Clubs" auch folgender Eintrag:

Hallo Herr Antwertinger,

beim Importtest Ihrer Daten ist mir folgender Datensatz aufgefallen:

`<Club ID="HE0100063" DistrictID="HE0000002" CountyID="HE0000023" StateID="HE" Type="Club" Name="HLV-Kreis Marburg-Biedenkopf" City="Marburg" StrippedName="" BankAccountIBAN="" BankAccountSWIFT="" TotalUsers="" ContactName="" ContactStreet="" ContactAdditional="" ContactZipCode="12345" ContactCity="Marburg" ContactPhone="" ContactEmail="" ContactWeb="https://marburg-biedenkopf.hlv.de/home/" InvoiceName="" InvoiceStreet="" InvoiceAdditional="" InvoiceZipCode="35085" InvoiceCity="Ebsdorfergrund" ClubDateStart="" ClubDateEnd="" LastUpdated="2019-09-04 10:04:38“>
`

Dabei handelt es sich um einen der Kreise im Hessischen Leichtathletik-Verband.

Die CountyID verweist auf den Eintrag des Kreises Marburg-Biedenkopf unter "Districts":

`<District ID="HE0000023" StateID="HE" CountyID="HE0000002" Name="Marburg-Biedenkopf" VATIN="" BankAccountIBAN="" BankAccountSWIFT="" ContactName="" ContactStreet="" ContactAdditional="" ContactZipCode="" ContactCity="" ContactPhone="" ContactEmail="" ContactWeb="" InvoiceStreet="" InvoiceAdditional="" InvoiceZipCode="" InvoiceCity="" LastUpdated="2016-03-01 14:31:22"/>`

In LA.Net habe ich nur eine Tabelle für jegliche Art von Organisationen.

Beim Import dieser Daten würde ich mir den Kreis doppelt, ins System holen.
Einmal als Kreis und das andere mal als Verein.

Stellt das ein Problem (in LA.Net) dar?
Bei den LV, die mit LA.Net als Meldesystem (und mit Phoenix als Mastersystem) arbeiten:
Ja, weil u.U. die falschen Organisationen als Veranstalter auftreten.
Bei den LV, die mit LA.Net als Genehmigungsystem (und mit Phoenix als Mastersystem) arbeiten:
Ja, weil der "Verein" "Kreis xy" andere Nutzerrollen hat, als der "Kreis" "xy".
Bei allen anderen LV:
Weiß ich noch nicht...

Stellt es andersherum ein Problem dar, wenn aus LA.Net der Kreis NUR als Kreis exportiert wird?
In Phoenix:
Dürfte eigentlich nicht. Zumindest im Moment kommt es dort nur auf die Hierarchie an, oder?
In LADV:
Weiß ich nicht!
Wenn ein Kreis (aus einem LV mit LA.Net) als Mastersystem in LADV einen Wettkampf einrichten will. Muss er dazu Kreis oder "Club" sein?
Unterscheidet LADV zwischen Kreisen in der Strucktur und Kreisen als Organisation?

**Comment by mschunk** [comment]
Meine Meinung dazu: Das Datenformat sieht für Verein/Kreise/Bezirke jeweils eigene Elemente vor. Einen Kreis ins Elment Verein zu packen ist daher falsch. Ein Krei ist kein Verein.

Auch Dinge wie `Type="Club" ` für einen Kreis ist definitif falsch. Zudem würde der Kreis eine Vereinsnummer bekommen.

**Comment by diwaffm** [comment]
In Phoenix muss ein Kreis auch als "Verein" angelegt werden, wenn der Kreis Rechungen bekommen soll.
Es gibt aber wohl eine Möglichkeit, diese "Vereine" vor dem Export auszufiltern...

**Comment by santwer** [comment]
In Phoenix wurde die Abfrage angepasst, so dass beim Export diese Kreise nicht mehr als Vereine im Export gelistet werden.
