### ISSUE TITLE
Themen von Phoenix II

### ISSUE THREAD

**Issue by santwer** [leichtathletik/dlv-datenaustausch#27]
Wir sind diese Woche intern eine Besprechnung auf ein paar offene Thmen gestoßen, welche wir noch anmerken müssen:

1.  Thema Abfrage Full: Für Phoenix II ist das erstellen dieser Abfrage ein sehr langer Prozess, da viele Tabellen join'nen. Dies liegt für uns als Problem sowohl beim erstellen als auch beim einlesen. Da ein so langer Prozess mit unseren aktuellen Herausforderungen im Perfomance-Bereich ein größeres Problem darstellt. Hier war die Anfrage wie das von anderer Seite geregelt wird?
2.  Für die Mastersystem-Tabelle werden zwei weitere Systeme Dfb-net und DLV-admin genannt. Wird das als Subsystem mitgeführt? Wird bei einem wechsel hier auch eine Schnittstelle eingeplfegt. 
3.  Ablauf für Tests mit anderen Systemen. Auf seite von Phoenix II liegt die Schnittstelle nun im Test. Hierzu würden wir von den gebauten Schnittstellen bestenfalls ebenfalls ein Testzugang um eben diese Perfomance nochmals im Auge zu behalten. 

Grüße
Sven Antwertinger

**Comment by diwaffm** [comment]
ad 2)
DFB-Net ist nur beim LV Westfalen relevant.
Die haben aber LA.Net als Mastersystem für die Lizenzverwaltung. Von daher sind die über LA.Net in den Datenaustausch eingebunden.

DLV-admin ist beim LV Rheinland im Einsatz.
Hier existiert eine Schnittstelle (über das "alte" DLV-Austauschformat) zu LA.Net.
D.h. ich habe die wettkampfrelevanten Stammdaten im System und könnte diese als "Mastersystem" zur Verfügung stellen.
Das würde zwar dem widersprechen, dass nur das Mastersystem (hier DLV-admin) Daten bereitstellt.
Einen anderen Weg sehe ich aber nicht. Ich kläre das mit dem LVR.

**Comment by diwaffm** [comment]
ad 1)
Die Abfrage aller Daten sehe ich auch problematisch.
Schon der komplette Abruf aller Daten EINES LV ist schon eine Herausforderung.
Das ist der Grund, weshalb ich mich damals mit Karl-Heinz Schulz auf die Übernahme der zuletzt geänderten Daten geeinigt hatte.

EINMALIG ist natürlich eine komplette Übernahme / Bereitstellung der Daten notwendig...

**Comment by mschunk** [comment]
> Für die Mastersystem-Tabelle werden zwei weitere Systeme Dfb-net und DLV-admin genannt. Wird das als Subsystem mitgeführt? Wird bei einem wechsel hier auch eine Schnittstelle eingeplfegt.

Das hatte ich auch schon als Problem Dokumentiert: https://github.com/leichtathletik/dlv-datenaustausch/issues/20

> Ablauf für Tests mit anderen Systemen. Auf seite von Phoenix II liegt die Schnittstelle nun im Test. Hierzu würden wir von den gebauten Schnittstellen bestenfalls ebenfalls ein Testzugang um eben diese Perfomance nochmals im Auge zu behalten.

Mein Vorschlag siehe hier: https://github.com/leichtathletik/dlv-datenaustausch/issues/29
Haben wir dem DLV so angeboten und wurde vom DLV beauftragt.

**Comment by mschunk** [comment]
> Full: Für Phoenix II ist das erstellen dieser Abfrage ein sehr langer Prozess, da viele Tabellen join'nen. Dies liegt für uns als Problem sowohl beim erstellen als auch beim einlesen. Da ein so langer Prozess mit unseren aktuellen Herausforderungen im Perfomance-Bereich ein größeres Problem darstellt. Hier war die Anfrage wie das von anderer Seite geregelt wird?

Der Abruf der Daten im "full mode" ist Teil der Schnittstelle und muss bereitgestellt werden. LADV wird nur diesen Abrufweg nutzen. Wir haben nicht vor die "changedSince" Daten zu verwenden.
Andersherum ist für uns die Bereitstellung der von Seltec und Phönix gewünmschte `changedSince` Daten extrem aufwendig. Es wurde so gewünscht, wir machen es. Ebenso erwarten wir im Austausch die "full mode" Daten. Jeder bekommt die Daten so wie er sie wünscht.

Zudem verstehe ich nicht wirklich wo das Problem bei den "full mode" Daten liegt. Das wird von Phönix und Seltec seit Jahren so bereitgestellt. Phönix liefert die Cosa SPV Daten was nichts anderes ist als "full mode" seit Jahren. Seltec liefert ATL/VER TXT oder CSV Daten seit Jahren. Auch "full mode" Daten.

> Dies liegt für uns als Problem sowohl beim erstellen als auch beim einlesen. Da ein so langer Prozess mit unseren aktuellen Herausforderungen im Perfomance-Bereich ein größeres Problem darstellt. Hier war die Anfrage wie das von anderer Seite geregelt wird?

Das hängt sehr stark davon ab wie man das implementiert. Man kann das natürlich alles in einer großen Transaktion machen .... aber ob das eine gute Idee ist? Zudem wäre es möglich die Daten einmal täglich in einem Batch Prozess für den Download vorzubereiten. Bei "full mode" ist das möglich. Bei "changedSince" nicht.

LADV führt die Stammdaten für Bayern, soweit mir bekannt der Verband mit am meisten Vereinen und Athletne. Wir erstellen die "Full mode" Daten seit Jahren täglich (in usnerem Datenformat). Wir haben damit kein Problem.

Was wir noch in die Schnittstellenbeschreibung aufnehmen könnten, dass ein System zu einem Zeitpunkt nur eine Anfrage aktiv haben darf. D.h. dass es nicht erlaubt ist mehrere Stammdaten Anfragen parallel zu machen, diese könnten dann mit HTTP 429 abgewiesen werden.

**Comment by diwaffm** [comment]
>
>Seltec liefert ATL/VER TXT oder CSV Daten seit Jahren. Auch "full mode" Daten.

LA.NET stellt die AKTUELLEN Lizenzdaten als CSV bereit.
DAS ist etwas anderes als der in der Sitzung Ende Juli von Dir definierte FULL MODE, der ALLE in diesem Jahr gültigen (auch die inzwischen beendeten bzw. noch nicht gültigen Lizenzen) enthalten soll...
