### ISSUE TITLE
Startrecht, Startpassnummer bei LV übergreifendem Vereinswechsel

### ISSUE THREAD

**Issue by UdoLaubDLV** [leichtathletik/dlv-datenaustausch#28]
Aktuell haben wir das Startrecht (Startpassnummer) wie folgt definiert (Athletes.xsd):

<xs:attribute type="String11Input"      name="LicenseNumber"        use="required"/> 

<xs:simpleType name="String11Input">
        <xs:restriction base="xs:string">
            <xs:minLength value="1" />
            <xs:maxLength value="11" />
        </xs:restriction>
    </xs:simpleType>

Können wir damit leben?
In den Ergebnissen steht aktuell der LV und diese Startrechtsnummer.
Wechselt ein Athlet den LV bekommt er eine neue Nummer (zumal die Nummern aktuell nicht deutschlandweit eindeutig sind).

Seine Ergebnisse sollte er aber behalten.

Damit  müsste man an einer Person im schlimmsten Fall 20 Startrechtsnummern verwalten?
Oder machen wir die Nummer deutschlandweit eindeutig und der Athlet behält die Nummer auch beim Vereinswechsel in einen anderen LV?
Oder schreiben wir in die Ergebnisse noch die PersonID?

**Comment by diwaffm** [comment]
Ich werde mal die Kollegen ins Bild setzen und Fragen, wie das umgesetzt bzw. geplant ist...

**Comment by diwaffm** [comment]
Die Wettkampfsoftware (TAF) kann mit externen IDs umgehen und sie beim Athleten speichern
In den aus aus LA.Net nach TAF übermittelten Stammdaten ist sie ebenfalls enthalten und dann mit dem Athleten im Wettkampf verknüpft.
Die trifft dann auch bei über die Stammdaten gemeldeten Athleten zu.

Auch in den importierten Meldungen sollte die PersonID mit übertragen werden. Das erspart die - theoretisch mögliche - Suche nach der PersonID über die Startrechtsnummer.

Die Leistungen des Athleten sind dann in der Datenbank, die die Grundlage für die Bestenliste bildet, mit der PersonID verknüpft.

**Comment by mschunk** [comment]
Also ich hatte das so verstanden, dass die `LicenseNumber` das ist was heute die Startrechtnummer/Startpassnummer/Athletennummer ist und ggf. auch in Ergebnislisten mit Angedruckt wird.
Die PersonID ist die neue GUID die nicht in Ergebnislisten oder irgendwo öffentlich auftaucht, allerdings jedem Mastersystem intern vorliegt und verwendet werden kann um Daten zusammenzuführen.

Die `LicenseNumber` kann sich verändern wenn ein Athlet den Landesverband wechselt. Die PersonID bleibt identisch.

**Comment by mschunk** [comment]
Noch ein Punk, wollen wir wirklich, dass die `LicenseNumber` ein String mit bis zu 11 Zeichen ist? D.h. ich kann Athletennummern wie: `AAAAAAAAAAA`, `$$$$$$$$$$$` oder `ßßßßßßßßßßß` vergeben?

Spricht etwas dagegen, es bei den heutigen Nummern 1 bis 9 999 999 (max. siebenstellig) zu belassen? Mehr kriegen wir in Ergebnislsiten nicht unter. StateID würde ich dann als separates Feld führen, so wie es heute in Ergebnislsiten auftaucht.

**Comment by diwaffm** [comment]
War nicht die Idee, die Lizenznummern genauso zu definieren, wie die ClubID?
Aber mir ist es auch recht, wenn es 2 getrennte Felder sind.
Intern handhabe ich das sowieso getrennt.
"HE" + 1234567

**Comment by diwaffm** [comment]
Der Einfachheit halber solten wir es hier bei EINEM Feld im Austausch belassen.
Zum jetztigen Zeitpunkt noch große Änderungen am Format vorzunehmen, halte ich nicht für sinnvoll!

**Comment by mschunk** [comment]
> War nicht die Idee, die Lizenznummern genauso zu definieren, wie die ClubID?

Ja, ich denke das war der Plan. Ich bin dafür für "LicenseNumber" die `MasterID` zu verwenden.

**Comment by UdoLaubDLV** [comment]
License wird mit MASTERID definiert
