### ISSUE TITLE
Altersklassen

### ISSUE THREAD

**Issue by mschunk** [leichtathletik/dlv-datenaustausch#3]
Für Altersklassen werden in dem vom DLV Vorgegebenen Datenformat drei Felder definiert:
AgeGroupCode
AgeGroupID
AgeGroupNameDE

Beispiel:
AgeGroupCode = MW
AgeGroupID = 58
AgeGroupNameDE = Männer/Frauen U20/U18

Verwendet wird allerdings nur die nicht verständliche `AgeGroupID `.

Vorschlag: 
AgeGroupID wird entfernt. AgeGroupCode wird in sprechende Konstanten überarbeitet. Beispiel siehe LADV Datenformate:
https://ladv.de/entwickler/altersklassen (Spalte LADV Code) bzw.
http://html.ladv.de/api/2016-01-24-LADV-Stammdaten-Datenformat.pdf

**Comment by mschunk** [comment]
TODO: codes pasten

**Comment by mschunk** [comment]
alle Anwesenden sind einverstanden.

**Comment by UdoLaubDLV** [comment]
Alle Altersklassen gemäß DLO so aufgenommen.
