### ISSUE TITLE
Datenabruf aus Phönix II / Unterschiede Schnittstellenbeschreibung

### ISSUE THREAD

**Issue by mschunk** [leichtathletik/dlv-datenaustausch#32]
Die Schnittstelle zum Datenabruf hält sich nicht an die Schnittstellenbeschreibung DLV/Laub.

Unterschiede:
- `athletes` (Dokumentation) vs. `person` (Phönix II)
- `clubs` (Dokumentation) vs. `club` (Phönix II)
- `stateID` (Pflichtparemeter) bei Phönix II nicht vorhanden
- neuer nicht Dokumentierter Parameter `reduced`

Die Schnittstelle zum Abruf der Stammdaten in Phönix sollte sich entweder an die Schnittstellendokumentation des DLV halten oder eine eigene Dokumentation die den Abruf beschreibt zur Verfügung stellen.

**Comment by santwer** [comment]
Für die folgenden Punkte haben wir Anpassungen durchgeführt:
> - athletes (Dokumentation) vs. person (Phönix II)
> - clubs (Dokumentation) vs. club (Phönix II)
Die Endpunkte bei Phoenix wurden somit geändert.

> - stateID (Pflichtparemeter) bei Phönix II nicht vorhanden
Hier wird dieses Feld immer gesetzt, wie in der Schnittstellenbeschreibung definiert. Somit ist das Datenformat auch valid nach XSD. Falls es wirklich an einem Punkt fehlt, bitte ich hier eine genauere Beschreibung des Problems zu definieren. Zumal der Parameter "StateID" definiert ist.

> - neuer nicht Dokumentierter Parameter reduced
Hier habe ich die Anpassungen für den Test definiert. Für eine Reduzierte Ausgabe wird dieser Parameter gesetzt. Allerdings wird Primäre die Ausgabe bei Phoenix über den Token definiert, welche Ansicht zu verfügung steht.

**Comment by mschunk** [comment]
> Hier wird dieses Feld immer gesetzt, wie in der Schnittstellenbeschreibung definiert. Somit ist das Datenformat auch valid nach XSD. Falls es wirklich an einem Punkt fehlt, bitte ich hier eine genauere Beschreibung des Problems zu definieren. Zumal der Parameter "StateID" definiert ist.

Ich habe nicht verstanden was mir das sagen soll. Wenn ich diese Abfrage durchführe:
```
curl -s -X GET -H "X-Auth-Token:<token>" "https://testlvs.it4sport.de/api/clubs?reduced=true&stateId=NI"
```

erhalte ich die Daten aus Sachsen und **NICHT** aus Niedersachsen. Damit verhält sich die Phönix Schnittstelle nicht wie Dokumentiert. Das ein Mastersystem sich nicht an die Schnitstellendokumentation hält ist laut Dokumentation **NICHT** vorgesehen. Wenn sich Phönix **NICHT** an die Schnittstellendokumentation hält, erwarte ich mindesteins eine Dokumentation wie die Schnittstelle zum Abruf funktioniert (sofern soetwas zulässig ist @UdoLaubDLV ?). Email und GitHub Issues sehen wir nicht als Dokumentation an.

> Hier habe ich die Anpassungen für den Test definiert. Für eine Reduzierte Ausgabe wird dieser Parameter gesetzt. Allerdings wird Primäre die Ausgabe bei Phoenix über den Token definiert, welche Ansicht zu verfügung steht.

`reduced` für Athleten auf dem Testsystem funktioniert soweit. Wir benötigen als nächstes die Livesystem Paramter/URLs. Testsystemdaten die nicht aktualisiert werden und Andere Pareamter zum Lifesystem benötigen sind nur beding hilfreich um den Abruf für Phönix livestem umzusetzen.
Wir sind blockiert bis Schnittstellen / Informationen für die Phönix Livesystem zur Verüfgugng stehen.

**Comment by UdoLaubDLV** [comment]
Falls in der Dokumentation etwas zu korrigieren ist, bitte melden. Danke Udo

**Comment by santwer** [comment]
> erhalte ich die Daten aus Sachsen und NICHT aus Niedersachsen. Damit verhält sich die Phönix Schnittstelle nicht wie Dokumentiert. Das ein Mastersystem sich nicht an die Schnitstellendokumentation hält ist laut Dokumentation NICHT vorgesehen. Wenn sich Phönix NICHT an die Schnittstellendokumentation hält, erwarte ich mindesteins eine Dokumentation wie die Schnittstelle zum Abruf funktioniert (sofern soetwas zulässig ist @UdoLaubDLV ?). Email und GitHub Issues sehen wir nicht als Dokumentation an.

Hierzu werde ich noch etwas diese Woche euch zukommen lassen. Leider ist es uns von der Architektur nicht direkt möglich den GET-Parameter den Verband zu steueren, bzw. das macht es unnötig kompliziert, da der Verband doppelt übertragen wird. Hierzu muss ich aber nochmal Rücksprache intern halten. 

> Wir benötigen als nächstes die Livesystem Paramter/URLs. Testsystemdaten die nicht aktualisiert werden und Andere Pareamter zum Lifesystem benötigen sind nur beding hilfreich um den Abruf für Phönix livestem umzusetzen.
Wir sind blockiert bis Schnittstellen / Informationen für die Phönix Livesystem zur Verüfgugng stehen.

Das können wir leider noch nicht machen, da wir das erst nach den ganzen Test übernehmen können. Zumal wir noch Performance der Schnittstelle Abschätzen und das intern noch besprochen werden muss. Ich erwarte, dass diese Livestellung in KW 48/49 passieren wird.

**Comment by santwer** [comment]
Nach internen Änderungen haben wir nun den Parameter `stateID` eingeführt. Die Daten von Niedersachen sind aber im Test noch nicht verfügbar, da es dort gerade noch Änderungen vor der Einführung der Schnittstelle gibt. 

`reduced` Parameter wurde soweit entfernt. Die API-Keys wurden angepasst, laut Schnittstellenbeschreibung wird an LADV und la.net2 nur die reduzierten Daten bereitgestellt. 

Livestellung findet diese Woche noch statt. Schnittstellen-Endpunkt und neue API-Keys versende ich sobald es Produktiv gestellt ist. 

Bitte prüfen und ggf. Issue schließen.

**Comment by mschunk** [comment]
Der Abruf funktioniert nun wie in der Schnittstellenbeschreibung dokumentiert.
