### ISSUE TITLE
Datenabruf aus Phönix II / Parameter reduced funktioniert nicht bei person

### ISSUE THREAD

**Issue by mschunk** [leichtathletik/dlv-datenaustausch#33]
`curl -s -X GET -H "X-Auth-Token:<Token>" "https://<host>/api/person?reduced=true"` funktioniert nicht. Es werden die "vollen" Daten übertragen. Das verletzt den Grundsatz der Datensparsamkeit des Datenschutzes.

**Comment by santwer** [comment]
Ich habe folgende Dinge angepasst. 
Parameter: reduced=true ist nun bei Personen ebenfalls verfügbar. 
Von uns wird über den Schlüssel vordefiniert ob eine Abfrage Full oder Reduziert angezeigt wird.
Somit funktioniert der paramter nur falls die Daten komplett angezeigt werden. 
Für den späteren Austausch wird dies auch über den Schlüssel definiert.

**Comment by mschunk** [comment]
`reduced` funktioniert nun bei Personen/athletes
