### ISSUE TITLE
Eindeutige Nummern: Kreise und Bezirke

### ISSUE THREAD

**Issue by diwaffm** [leichtathletik/dlv-datenaustausch#34]
Auch beim ersten Augenschein der Vereinsdaten aus Bayern ist mir aufgefallen, dass es Vereine gibt, die die gleiche ID haben, wie ein Kreis:

Z.B. 
Club ID="BY0002100" DistrictID="BY0002100" CountyID="BY0002000" StateID="BY" Type="Club" Name="TSV Abensberg" City="Abensberg"

oder

Club ID="BY0002300" DistrictID="BY0002300" CountyID="BY0002000" StateID="BY" Type="Club" Name="TSV Aidenbach" City="Aidenbach"

Dies widerspricht der Forderung in der Schnittstellenbeschreibung: "Die IDs für Kreise, Bezirke und Vereine dürfen sich nicht überschneiden."

Auch hier wäre es sinnvoll, eine von der im allgemeinen Gebrauch lösgelöste _interne_ ID für die Verknüpfung der Organisationen untereinander zu verwenden...

Also beispielsweise, wie in https://github.com/leichtathletik/dlv-datenaustausch/issues/30 vorgeschlagen, eine GUID...

**Comment by mschunk** [comment]
> Auch beim ersten Augenschein der Vereinsdaten aus Bayern ist mir aufgefallen, dass es Vereine gibt, die die gleiche ID haben, wie ein Kreis:

> Z.B.

Es würde mich sehr wundern wenn dem so ist. Gibt es dafür ein Beispiel?

**Comment by diwaffm** [comment]
s.o.
Da ist was beim Einfügen und als Code markieren falsch gelaufen...

**Comment by mschunk** [comment]
Das sich Kreis und Vereinsnummern überschneiden sollte nicht sein. Werde ich mit dem LV klären.

**Comment by mschunk** [comment]
Es ist jetzt sichergestellt das Verein/Kreis/Bezirk nummern eindeutig sind.
