### ISSUE TITLE
LicenseClubId bei LGs

### ISSUE THREAD

**Issue by diwaffm** [leichtathletik/dlv-datenaustausch#35]
Wenn ich mir die Personen und Lizenzdaten einer von LADV übermittelten Person anschaue, die ein Startrecht für eine LG hat, so fällt auf, dass LicenseClubID und HomeClubID IDENTISCH sind.
Die Lizenz ist also für den Stammverein ausgestellt.

```
         <Person PersonID="4d50845d-15a8-42c4-943e-9efe973869dd" FirstName="Christina" LastName="Hering" Gender="F" Yearofbirth="1994" FirstNationality="GER" IsActive="" ClubID="BY0001131">
             <Licenses>
                 <License LicenseNumber="BY0252213" LicenseClubID="BY0001131" LicenseStart="2007-03-05" HomeClubID="BY0001131"/>
             </Licenses>
     	</Person>
```
 

In Phoenix unterscheiden sich bei einer Person mit Startrecht für die LG LicenseClubID und HomeClubID.
Das ist auch bei Daten, die ich von dlv-admin erhalten so - und auch der Export aus LA.Net wird so wie bei Phoenix aufgebaut sein.

```
		<Person PersonID="BD06D0C9-2C13-411B-BFFC-3A8FDFA4A71B" FirstName="Lennard" LastName="Wagner" Gender="M" Yearofbirth="1999" FirstNationality="GER" IsActive="1" ClubID="HE0000489" LastUpdated="2016-04-14 13:18:39">
			<Licenses>
				<License LicenseNumber="HE0103460" LicenseClubID="HE0000076" LicenseStart="2008-05-16" HomeClubID="HE0000489" LastUpdated="2019-02-04 14:11:20" />
			</Licenses>
		</Person>
```

Meiner Meinung nach müsste die Ausgabe bei LADV angepasst werden, da sie inhaltlich nicht korrekt ist.
Ein Athlet, dessen Stammverein (in seiner Altersklasse) Mitglied in einer LG ist, hat auschließlich ein Startrecht für die LG.

**Comment by mschunk** [comment]
fixed:
```xml
<Person PersonID="4d50845d-15a8-42c4-943e-9efe973869dd" FirstName="Christina" LastName="Hering" Gender="F" Yearofbirth="1994" FirstNationality="GER" IsActive="" ClubID="BY0001131">
	<Licenses>
		<License LicenseNumber="BY0252213" LicenseClubID="BY0001126" LicenseStart="2007-03-05" HomeClubID="BY0001131"/>
	</Licenses>
</Person>
```

**Comment by mschunk** [comment]
Da es keien anderweitige Rückmeldung gab: Closed.
