### ISSUE TITLE
FirstNationality="GER"

### ISSUE THREAD

**Issue by mschunk** [leichtathletik/dlv-datenaustausch#38]
Funktioniert die Ausgabe der Nationalität in Phönix? 100% aller Datensätze haben die Nationalität `GER`. 

Athleten die bisher eine andere Nationalität hatten werden auf `GER` umgestellt.

Beispiel:
```
138654: G. Polushko [Nationalität 'UKR'->'GER']
138564: J. Smely, [Nationalität 'CZE'->'GER']
141697: W. Zarzycki, [Nationalität 'POL'->'GER']
```

20+ weitere Athleten.

**Comment by santwer** [comment]
Habe das Problem gelöst, bitte einmal prüfen und folglich das Issue schließen.

**Comment by mschunk** [comment]
Im Datenabruf 16.11.2019 sind keine Unterschiede bzl. Nationalitäten mit den LADV Bestandsdaten mehr sichtbar.
