### ISSUE TITLE
viele gelöschte aktive Athleten

### ISSUE THREAD

**Issue by mschunk** [leichtathletik/dlv-datenaustausch#40]
Datenabgleich der Phönix II Testdaten zeigt 50+ gelöschte Athleten die in 2019 aktiv waren und Leistungen haben. Das ist sehr ungewöhnlich das so viele aktiv Athleten währen des Jahres abgemeldet werden.

Das sollte überprüft werden, könnte ein Ausgabefehler sein. Wir haben seit Jahren ähnliche Probleme mit den COSA SPV Daten in Württemberg. Das Problem in Württemberg habe ich bereits mehrfach gemeldet.

Beispiele:
```
140236: L. Bensch, W, 2004, GER [Daten vorhanden, Startpassnummer entfernt]
140237: M. Tamme, W, 2005, GER [Daten vorhanden, Startpassnummer entfernt]
140238: J. Ufer, M, 2005, GER [Daten vorhanden, Startpassnummer entfernt]
140337: L. Windisch, M, 2005, GER [Daten vorhanden, Startpassnummer entfernt]
140503: A. Wistuba, W, 2004, GER [Daten vorhanden, Startpassnummer entfernt]
140676: P. Schreiber, W, 2004, GER [Daten vorhanden, Startpassnummer entfernt]
ca. 50 weitere
```

**Comment by santwer** [comment]
Das Problem ist gelöst. Bitte prüfen und Issue schließen, wenn gelöst.

**Comment by mschunk** [comment]
Im Datenabruf am 16.11. sind es nur noch 4 gelöschte Athleten.
