### ISSUE TITLE
e.V. oder nicht e.V. / Probleme mit Vereinsnamen

### ISSUE THREAD

**Issue by mschunk** [leichtathletik/dlv-datenaustausch#41]
Abgleich mit den Phönix II Testdaten zeigt das nun bei vielen Vereinen die Rechtsform im Namen ergänzt wird. Beispiele:
```
1: LSV Niesky e.V. [Name: 'LSV Niesky'->'LSV Niesky e.V.']
9: TSV Dresden e.V. [Name: 'TSV Dresden'->'TSV Dresden e.V.']
10: TVL Freiberg e.V. [Name: 'TVL Freiberg'->'TVL Freiberg e.V.']
12: Post SV Dresden e.V. [Name: 'Post SV Dresden'->'Post SV Dresden e.V.']
14: SC DHfK Leipzig e.V. [Name: 'SC DHfK Leipzig'->'SC DHfK Leipzig e.V.']
ca, 50 weitere Vereine
```

Soweit mir bekannt, müssen Leichathletik Vereine e.V. sein, die Namenserweiterung wird allerdings i.d.R. nicht im Wettkampfbetrieb mitgeführt. Es sollte überprüft werden ob gewünscht ist, dass nun auf einmal bei vielen Vereinen das e.V. für den Wettkampbetrieb, Meldungen, Teuilnehmerlisten, Ergebnislisten mit übermittelt wird und sich so viele Vereinsnamen ändern.

**Comment by diwaffm** [comment]
ICH würde das "e.V." und andere Kürzel weglassen. Allerdings sollte nicht in die Entscheidung des Vereins eingegriffen werden.

Es gibt Vereine, die legen großen Wert darauf, dass das "e.V." auch auf den Listen steht.
Andere tun das nicht...
Es gibt auch - altrechtliche Vereine - die keine e.V. sind.
Diese tragen manchmal das Kürzel "j.P." am Ende des Namens. Und auch hier gibt es welche, die möchten, dass das Kürzel verwendet wird und andere, denen es egal ist...

**Comment by santwer** [comment]
In Phoenix II werden die Vereine mit e.V. aus rechtlichen Gründen vom Verband geplegt. Wir sehen keinen Grund den Vereinsnamen ohne diesen auszugeben. Zumal es bislang keine definition dazu gibt.

**Comment by mschunk** [comment]
Im Prinzip gibt es hier zwei konkurrierende Anforderungen:

- Im Sportbetrieb ist es üblich, dass das `e.V.` nicht miteführt wird, da es eher stört. Dies gilt bis auf wenige Ausnahmen, einzelne Vereine bestehen auf das `e.V.`.
- Für Rechnungstellugn ist es oft erforderlich den korrekten Vereinsnamen mit `e.V.` bereitzustellen. Finanzämter bestehen tlw. darauf um Rechnungen anzuerkennen.

Eine Mögliche Lösung wäre, ein weiteres optionales Attribut im Elemen Club einzuführen, dass Rechtsform (legalform oder legalstatus) heißt. Dann lassen sich beide Anforderungen abbilden.

### Beispiele

Im Sportbetrieb wird "TSV Musterverein" verwendet. Für Rechnungen wird "TSV Musterverein e.V." verwendet:
```xml
<club name="TSV Musterverein" legalstatus="e.V." ...
```


Im Sportbetrieb wird "TSV Musterverein "e.V." verwendet. Für Rechnungen wird "TSV Musterverein e.V." verwendet (Attribut `legelstatus` fehlt):
```xml
<club name="TSV Musterverein e.V."  ...
```

**Comment by mschunk** [comment]
Auch in Württemberg wird bei einer ganzen Reihe Vereine das "e.V." ergänzt:

```
7528: Name: 'FC Kluftern'->'FC Kluftern 1933 e.V.'
2376: Name: 'TSV Bad Rietenau'->'TSV Bad Rietenau 1921 e.V.'
6340: Name: 'SV Dürbheim'->'Sportverein Dürbheim e.V.'
3774: Name: 'ASC Ulm/Neu-Ulm'->'ASC Ulm/Neu-Ulm 011 e.V.'
4162: Name: 'TSV Heumaden'->'TSV Heumaden 1893 e.V.'
```
Weitere ...

**Comment by santwer** [comment]
Einen Nachtrag hierzu. 
Es ist nun klar, warum dies bei allen Verbänden vorkommt, dass die Vereine einen anderen Namen haben. 
Wir führen in Phoenix drei Vereinsnamen, insofern der Verband das möchte und macht. 
1. Vereinsname (auch rechtlicher Name also ist e.V. notwendig)
2. Vereinsname nach COSA
3. Vereinsname Kurz nach COSA
![grafik](https://user-images.githubusercontent.com/39012551/70696296-b17a3c80-1cc3-11ea-8d2d-235cfca8f6f7.png)

Wäre es hier nicht besser, wenn Vereinsname Kurz, das auch in der Schnittstelle mitübertragen wird zum Abgleich zu nehmen? 
Leider führt bislang z.b. Hessen noch keine Cosa Daten in Phoenix, heißt hier fehlt es auch uns an Kurznamen. Aber für WÜ und NI wäre das primär eine Option den Datenaustausch durchzuführen. 
Wir können auch, falls Vorhanden, den Cosa-Namen als Vereinsname Kurz übergeben. 
Ich denke, dass für den Namen der richtige Name für den Verein wichtig ist zu übertragen, da es für die Rechnungsschreibung erforderlch ist.

**Comment by mschunk** [comment]
### Ist Zustand
Das DLV Stammdatenformat sieht derzeit zwei Vereinsnamen vor:

- Name, max 200 Zeichem, Pflichtfeld
- Kurzname (shotname in xml), max 30 Zeichen, Optional

Eine Erklärung ob es sich dabei um den/die "Rechtliche-Namen" für die Rechnungstelltung oder  den Namen für den Sportbetrieb handelt ist nicht vorhanden.

Probleme:
- Es gibt keine Vorgabe ob / wie der Vereinsnamen für den Sportbetrieb oder der Rechtliche-Vereinsname zu verwenden ist. Jedes Mastersystem kann machen was es will. Andere Systeme die die Daten verwenden haben keine Ahnung welcher Vereinsname für welchen Zweck zu verwenden ist. Chaos.
- Das Mastersystem Phönix kann mehr als zwei Vereinsnamen führen und gibt über andere Datenformate (COSA SPV) tlw. andere Vereinsnamen weiter.

### Lösungsvorschlag 1 (Erweiterung Datenformat)

Das Datenformat wird um ein optionales Feld (Attribut im Element-Club) erweitert: legalname.

Wir hätten dann drei Vereinsnamen:
- Name, max 200 Zeichem, Pflichtfeld
- Kurzname (shotname in xml), max 30 Zeichen, Optional
- Legalname, max XXX Zeichen, Optional

Desweiteren wird folgende Erklärung in der Schnittstellendokumentation ergänzt:
`Name` - Der Vereinsname wie er im Sportbetrieb verwendet wird. Dieser Namen wird in Ergebnislisten, Teilnehmerlisten, Wettkampfliste, Statistiken etc. verwendet.
`Kurzname (optional)` - Der Kurzname ersetzt den Namen, wenn dieser länger als 30 Zeichen ist und wird an dessen stelle in Ergebnislisten, Teilnehmerlisten, Wettkampfliste, Statistiken etc. verwendet. Der Kurzname soll ein sinnvoller Name sein, nicht einfach der Name nach 30 Zeichen abgeschnitten.
`Legalname (optional)` - Der Rechtliche Vereinsname wie er für Rechnungstellung zu verwenden ist. Ist kein Rechtlicher Vereinsname vorhanden, dann wird der Name für die Rechnungstellung verwendet.

### Lösungsvorschlag 2 (Erklärung in der Dokumentation)

Vereinsnamen weiterhin:
- Name, max 200 Zeichem, Pflichtfeld
- Kurzname (shotname in xml), max 30 Zeichen, Optional

Desweiteren wird folgende Erklärung in der Schnittstellendokumentation ergänzt:
`Name` - Der Rechtliche Vereinsname wie er für die Rechnungstellung verwendet wird. Ist kein Kurzname (shortname) vorhanden, wird der Name auch für den Sportbetrieb verwendet. Wenn der Name länger als 30 Zeichen ist, muss ein Kurzname angegeben werden.
`Kurzname (optional)` - Der Kurzname ist der Vereinsname für den Sportbetrieb und wird in Ergebnislisten, Teilnehmerlisten, Wettkampfliste, Statistiken etc. verwendet. Der Kurzname soll ein sinnvoller Name sein, nicht einfach der Name nach 30 Zeichen abgeschnitten.

@UdoLaubDLV an sich ist es Deine Aufgabe als Eigentümer des Datenformates hier für Klarheit zu sorgen.

**Comment by mschunk** [comment]
LADV würde Lösungsvorschlag 1 bevorzugen. Mit Lösungsvorschlag 2 können wir auch leben.

**Comment by MartinKallmeyer** [comment]
Der LVBY hat generell das selbe Problem, dass einige Vereine auf das "e.V." bestehen (wobei nur für die Rechnungsstellung). Beide von Marc skizzierten Vorschläge sind für mich als LV in Ordnung und ich denke auch für die Softwarehäuser mit wenig Aufwand (Vorschlag 2 vsl. noch weniger)  umsetzbar.

**Comment by UlrichMichel** [comment]
Niedersachsen hat das gleiche Problem und wäre für Vorschlag 1 (da die Daten in Phoenix bereitstehen). Vorschlag 2 wäre aber auch ok.

**Comment by mschunk** [comment]
LV Baden (Saskia Diel): aus unserer Sicht klingt "Lösungsvorschlag 1 (Erweiterung Datenformat)" sinnvoll.

**Comment by diwaffm** [comment]
In LA.Net pflegen wir **einen** langen Vereinsnamen.
Dieser wird sowohl für die Rechnungsstellung als auch für den Sportbetrieb verwendet. Dabei richtet sich der Inhalt nach den Wünschen der Vereine.

Da der Stammdatenaustausch **nur** die Daten fürden Sportbetrieb beinhaltet, sehe ich keine Notwendigkeit, zum jetzigen Zeitpunkt Änderungen am Austauschformat vorzunehmen.

Hat ein Mastersystem mehrere Varianten des Vereinsnamens, so liefert es an der Schnittstelle den für den Sportbetrieb relevanten.

**Comment by mschunk** [comment]
> Da der Stammdatenaustausch nur die Daten fürden Sportbetrieb beinhaltet,

Der Datenaustausch beinhaltet sehr wohl Daten für Rechnungstelltung. Das Element Club hat folgende Attribute:
- InvoiceName
- InvoiceStreet
- InvoiceAdditional
- InvoiceZipCode
- InvoiceCity
- BankAccountIBAN
- BankAccountSWIFT

Der wesentliche Teil, der Vereinsname für die Rechnungstellung **fehlt**.

LADV erstellt in vielen Landesverbänden die Rechnungen für die Veranstaltungsanmeldung. Dafür ist es notwendig das wir den Vereinsnamen wie er auf Rechnungen auftauchen muss erhalten, insbesondere wenn sich dieser von dem im Sportbetrieb verwendeten Namen unterscheidet. 

> Hat ein Mastersystem mehrere Varianten des Vereinsnamens, so liefert es an der Schnittstelle den für den Sportbetrieb relevanten.

Phönix tut dies nicht.

**Comment by mschunk** [comment]
LV Württemberg (Markus Reichle): Bezüglich der Vereinsnamen --> ich würde auch deinen ersten Vorschlag präferieren!

**Comment by santwer** [comment]
Die Schnittstelle bezieht nun die Daten wie 04.03.2020 besprochen.
Name sofern gepfegt wird mit dem "Cosa"-Namen für den Spielbetrieb bestückt. InvoiceName beinhaltet den Rechtlichen Namen des Vereins wie in Phoenix gepflegt.

**Comment by UlrichMichel** [comment]
***************** AUTO - REPLY *********************************

Vielen Dank für Ihre Nachricht.

Leider kann ich diese (aus lange geplanten "Urlaubs"gründen) derzeit nicht annehmen und bearbeiten.  Ab Dienstag, 14.04.2020 (geplant), bin ich wieder in der Geschäftsstelle erreichbar und werde mich dann schnellstmöglich um Ihr Anliegen kümmern. In dringenden Angelegenheiten können Sie sich an die Zentrale wenden (info@nlv-la.de;  Tel. 0511 - 33 89 00).




Viele Grüße und bleibt gesund

Ulrich Michel
Niedersächsischer 
Leichtathletik - Verband e.V. 
Ferdinand-Wilhelm-Fricke-Weg 10, 30169 Hannover 
Tel. 0511 / 33 89 0 - 16,  Fax 0511 / 33 89 0 - 19 
email: michel@nlv-la.de
Homepage: http://www.nlv-la.de


Präsident: Uwe Schünemann
Vereinsregisternummer 8204, Amtsgericht Hannover 
USt-IdNr. DE115512889
