### ISSUE TITLE
Anzeige Mode Full - delta

### ISSUE THREAD

**Issue by santwer** [leichtathletik/dlv-datenaustausch#42]
Beim Abrufen von LADV mit den GET-Parameter changedSince bekome ich bei der Antwort, immer folgenden Head
```
    <Request>
        <Mastersystem>LADV</Mastersystem>
        <Created>2019-11-15 14:38:39</Created>
        <Mode>full</Mode>
    </Request>
```
Es gibt mir also full anstelle von delta zurück. Ich kann also anhand der Antwort nicht erkennen um welche Antwort es sich tatsächlich handelt.

**Comment by mschunk** [comment]
fixed

**Comment by santwer** [comment]
Abruf stimmt nun.
