### ISSUE TITLE
Stammdaten von LADV

### ISSUE THREAD

**Issue by santwer** [leichtathletik/dlv-datenaustausch#43]
Beim Abruf von den Daten von LADV ist mir noch nicht klar, ob hier noch nicht alle Daten übertragen werden. Oder ob diese Daten nicht geplegt werden. 
So ist das Feld `Birthday` bei den Athleten nicht vorhanden, allerdings alle anderen Kontaktdaten.
Außerdem werden Bankdaten von Vereinen sofern vorhanden übertragen. 

Für Phoenix II ist das abarbeiten von den Geburtstagen für die Pässe recht wichtig, zumal für die Verwendung der DLV das auch ein wichtiger Punkt ist. Wir können zwar `Yearofbirth` hinterlegen, hier aber wieder mit Einschränkungen.

**Comment by mschunk** [comment]
`Birthday` hatte in der full Ausgabe der Daten gefehlt. Ist nun ergänzt.

Alle anderen Daten werden, soweit vorhanden, bereitgestellt.

**Comment by santwer** [comment]
´Birthdate´ ist nun auch einlesbar.
