### ISSUE TITLE
Phoenix II => LA.Net2

### ISSUE THREAD

**Issue by diwaffm** [leichtathletik/dlv-datenaustausch#45]
Beim Import der Hessischen Daten ist mir aufgefallen, dass es vorkommen kann (obwohl es inhaltlich eigentlich nicht sein darf), dass bei StGs MemberAgeGroups für die verschiedenen Mitgliedsvereine einer StG unterschiedlich gefüllt ist.

Konkret habe ich einen Fall (schon mit dem LV besprochen), bei dem für den einen Verein KEINE MemberAgeGroups hinterlegt sind, für den anderen aber schon:

&lt;Club ID="HE0002103" DistrictID="HE0000003" CountyID="HE0000034" StateID="HE" Type="STG" Name="StG Isenburg/Heusenstamm" City="Neu-Isenburg" LastUpdated="2018-10-30 14:27:09"&gt;
&lt;MemberClubs&gt;
&lt;MemberClub ID="HE0000602" Name="TV 1861 Neu-Isenburg" MemberDateStart="2014-01-01"/&gt;
&lt;MemberClub ID="HE0000611" Name="TSV Heusenstamm" MemberDateStart="2014-01-01" MemberAgeGroups="SENIORENW U16U14M U16U14W U20U18M SENIORENM AKTIVEM"/&gt;
&lt;/MemberClubs&gt;
&lt;/Club&gt;

Solche Inhaltlichen Fehler sollten VOR dem Export abgefangen werden.

**Comment by diwaffm** [comment]
Beim (Komplett-) Import der Hessischen Athleten gab es (mindestens) eine Athletin, die einem Verein zugeordnet ist, der NICHT in der Liste der Vereine enthalten ist und die auch eine Lizenz für diesen Verein hat...

Auch hier gilt meiner Meinung nach: DAS sollte nicht passieren und müsste vor dem Export abgefangen werden...

Es handelt sich um die folgende Lizenz:
<License LicenseNumber="HE1911962" LicenseClubID="HE0009816" LicenseStart="2016-05-24" HomeClubID="HE0009816" LastUpdated="2016-05-24 13:46:14">

**Comment by santwer** [comment]
> Beim Import der Hessischen Daten ist mir aufgefallen, dass es vorkommen kann (obwohl es inhaltlich eigentlich nicht sein darf), dass bei StGs MemberAgeGroups für die verschiedenen Mitgliedsvereine einer StG unterschiedlich gefüllt ist.

Ich habe gesehen, dass dies schon in der Produktivumgebung korrigiert ist.

> Solche Inhaltlichen Fehler sollten VOR dem Export abgefangen werden.

Das wird angepasst und folglich nicht mehr beim Export dargestellt. 

> Beim (Komplett-) Import der Hessischen Athleten gab es (mindestens) eine Athletin, die einem Verein zugeordnet ist, der NICHT in der Liste der Vereine enthalten ist und die auch eine Lizenz für diesen Verein hat...

> Es handelt sich um die folgende Lizenz:

Hier benötige ich die Lizenz um den Fall zu untersuchen.

**Comment by diwaffm** [comment]
Ich vergesse immer wieder, dass hier Dinge in spitzen Klammern nicht angezeigt werden ;-)

License LicenseNumber="HE1911962" LicenseClubID="HE0009816" LicenseStart="2016-05-24" HomeClubID="HE0009816" LastUpdated="2016-05-24 13:46:14"

**Comment by mschunk** [comment]
> Ich vergesse immer wieder, dass hier Dinge in spitzen Klammern nicht angezeigt werden ;-)

Tipp: https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#code-and-syntax-highlighting

**Comment by santwer** [comment]
> Es handelt sich um die folgende Lizenz:
License LicenseNumber="HE1911962" LicenseClubID="HE0009816" LicenseStart="2016-05-24" HomeClubID="HE0009816" LastUpdated="2016-05-24 13:46:14"

Solch ein Fall sollte nun nicht mehr im Export auftauchen. Pässe von nicht Vereinen des Verbandes werden herausgefiltert.

**Comment by santwer** [comment]
Falls dies nicht mehr aktuell ist, bitte ich darum das zu schließen

**Comment by diwaffm** [comment]
Ich mach mal zu...
Hessen muss ich mir noch anschauen (wg. der Übernahme der GUIDs...)
