### ISSUE TITLE
Phönix II: 6 Verbänden ist die clubs XML nicht XSD konform

### ISSUE THREAD

**Issue by mschunk** [leichtathletik/dlv-datenaustausch#47]
Baden:
```
cvc-maxLength-valid: Wert 'Sport- & Gymnastikverein Sinsheim' mit Länge = '33' ist nicht Facet-gültig in Bezug auf maxLength '30' für Typ 'String30Data'
```

Brandenburg:
```
cvc-maxLength-valid: Wert 'SV Blau-Weiß Straupitz (Spreewald)' mit Länge = '34' ist nicht Facet-gültig in Bezug auf maxLength '30' für Typ 'String30Data'.>
```

Bremen:
```
cvc-complex-type.4: Attribut 'MemberAgeGroups' muss in Element 'MemberClub' vorkommen.
```

Hessen:
```
cvc-pattern-valid: Wert '2019-01-01 00:00:00' ist nicht Facet-gültig in Bezug auf Muster '(19|20)\d\d-(0[1-9]|1[012])-(0[1-9]|[12][0-9]|3[01])' für Typ 'SQLDate'.
```

Sachsen:
```
cvc-pattern-valid: Wert '2018-12-31 00:00:00' ist nicht Facet-gültig in Bezug auf Muster '(19|20)\d\d-(0[1-9]|1[012])-(0[1-9]|[12][0-9]|3[01])' für Typ 'SQLDate'.>
```

Württemberg:
```
cvc-pattern-valid: Wert '2016-08-03 00:00:00' ist nicht Facet-gültig in Bezug auf Muster '(19|20)\d\d-(0[1-9]|1[012])-(0[1-9]|[12][0-9]|3[01])' für Typ 'SQLDate'.
```

**Comment by santwer** [comment]
Alle Punkte bis auf den Punkt mit Bremen sind gelöst. 
Grund: Die Daten in Bremen weißen noch mehr Fehler auf. Ich werde die Schnittstelle zu Bremen nicht schließen, es scheint, als sei die Migration der Daten erst passiert und es müssen hier noch anpassungen gemacht werden. Dazu mehr sobald auch ich mehr informationen habe.

**Comment by mschunk** [comment]
Test am 24.11.:

Baden:
```
cvc-maxLength-valid: Wert 'Sport- & Gymnastikverein Sinsheim' mit Länge = '33' ist nicht Facet-gültig in Bezug auf maxLength '30' für Typ 'String30Data'.>
```

Brandenburg:
```
cvc-maxLength-valid: Wert 'SV Blau-Weiß Straupitz (Spreewald)' mit Länge = '34' ist nicht Facet-gültig in Bezug auf maxLength '30' für Typ 'String30Data'.
```

Bremen:
```
cvc-complex-type.4: Attribut 'MemberAgeGroups' muss in Element 'MemberClub' vorkommen.
```

Württemberg:
```
Attribut 'MemberAgeGroups' muss in Element 'MemberClub' vorkommen.
```


> Alle Punkte bis auf den Punkt mit Bremen sind gelöst.

Nein sind sie nicht. Bzl. Bremen - dafür gibt es HTTP 404. Wenn Daten ausgeliefert werden, dann sollten diese nach bestem Wissen Schnittstellenm konform sein.

**Comment by santwer** [comment]
Habe auch hier die Anpassungen gemacht gehabt. Und die Daten sind bei mir nun XSD-Konform.
Bitte Hier prüfen.
> Bzl. Bremen - dafür gibt es HTTP 404. Wenn Daten ausgeliefert werden, dann sollten diese nach bestem Wissen Schnittstellenm konform sein.
Habe nun somit die Schnittstelle für Bremen geschlossen. Sobald hier ein neuer Stand vorhanden ist, wird diese wieder frei gegeben.

**Comment by mschunk** [comment]
Datenabruf am 29.11.:

Baden:
`cvc-pattern-valid: Wert 'gabi.kief@gmx.de; gabi@marathonteam-ketsch.de' ist nicht Facet-gültig in Bezug auf Muster '([äöüÄÖÜßa-zA-Z0-9._%+-]+@[äöüÄÖÜßa-zA-Z0-9.-]+\.[a-zA-Z]{2,10})' für Typ 'EmailAddress'.`

**Comment by mschunk** [comment]
Datenabruf am 05.12 - alle XML sind XSD konform

**Comment by mschunk** [comment]
Datenabruf 17.12. 13:34 Uhr. Die Vereins XML Daten für Württemberg sind nicht XSD konform:
```
cvc-complex-type.4: Attribut 'MemberAgeGroups' muss in Element 'MemberClub' vorkommen.
```

```xml
<?xml version="1.0" encoding="UTF-8"?>
<StateData>
  <Request>
    <Mastersystem>Phoenix II</Mastersystem>
    <Created>2019-12-17 02:00:02</Created>
    <DateCUStart>2019-01-01</DateCUStart>
    <DateCUEnd>2020-01-02</DateCUEnd>
    <Mode>full</Mode>
  </Request>

```

**Comment by santwer** [comment]
Wir haben dies gelöst. Es sollte nicht mehr vorkommen. Es wird nun gefiltert, ob die Daten richtig gesetzt sind und es wird gegen die XSD geprüft vor dem output.

**Comment by mschunk** [comment]
Beim Abruf heute waren die Vereins XML von Württemberg/Niedersachsen/Sachsen/Hessen XSD konform.
