### ISSUE TITLE
Phönix II: 2 Verbänden ist die athletes XML nicht XSD konform

### ISSUE THREAD

**Issue by mschunk** [leichtathletik/dlv-datenaustausch#48]
Hessen:
```
cvc-pattern-valid: Wert '-' ist nicht Facet-gültig in Bezug auf Muster '[A-Z]{3}' für Typ 'CountryCode'.
```

Württemberg:
```
cvc-maxInclusive-valid: Wert '2206' ist nicht Facet-gültig in Bezug auf maxInclusive '2100' für Typ 'YearOfBirth'.
```

**Comment by santwer** [comment]
Diese Punkte sind nun gelöst.
Um letzteren Punkt handelt es sich um einen Eingabefehler, diese werden nun herausgefiltert, sodass die Daten weiterhin XSD confirm bleiben.

**Comment by mschunk** [comment]
Nachtest am 24.11.:

Hessen:
```
cvc-maxInclusive-valid: Wert '2196' ist nicht Facet-gültig in Bezug auf maxInclusive '2100' für Typ 'YearOfBirth'.>
```

Württemberg:
```
cvc-maxInclusive-valid: Wert '2204' ist nicht Facet-gültig in Bezug auf maxInclusive '2100' für Typ 'YearOfBirth'.>
```

> Diese Punkte sind nun gelöst.

Now you are talking.

**Comment by santwer** [comment]
Nochmalige Korrektur. Der Job der die Ablage der XML Daten macht, hat sich nicht korrekt ausgeführt, daher wurde die Abfrage vom 22. statt vom 24. angezeigt. Dies konnte ich nun Abfangen und es gibt hier nun keinen Fehler mehr. 
Bitte gerne nochmals Prüfen. Alle tests mit den XSD Daten waren bei mir nun positiv.

**Comment by mschunk** [comment]
Die Daten aus Sachsen, Württemberg und Hessen sind nun ok.

**Comment by mschunk** [comment]
Datenabruf am 01.12.2019

Niedersachsen:
```
cvc-minInclusive-valid: Wert '1907' ist nicht Facet-gültig in Bezug auf minInclusive '1910' für Typ 'YearOfBirth'.>
```

**Comment by mschunk** [comment]
Datenabruf am 05.12.2019 - XMLs sind alle XSD konform
