### ISSUE TITLE
Person: Birthdate

### ISSUE THREAD

**Issue by mschunk** [leichtathletik/dlv-datenaustausch#5]
Laut Dokumentation ist für Personen das Geburtsdatum "required". Für die Einhaltung des Datenschutzes ist allerdings für Drittsysteme nur das Geburtsjahr relevant. XSD Definition ist entsprechend anzupassen, es muss Geburtsdatum und Geburtsjahr möglich sein.

**Comment by mschunk** [comment]
Zusätzliches Feld: birthYear
birthYear und birthData sind beide optional nach XSD. Laut Dokumentatuon muss ein Feld gesetzt sein.

**Comment by mschunk** [comment]
Zusätzliches Feld: birthYear (required nach XSD)
birthDate wird optional.
Alle Datensätze sollen konsistent sein (birthDate wird bei allen mitgegeben oder bei keinem Datensatz).

**Comment by UdoLaubDLV** [comment]
In die Dokumentation und XSD so aufgenommen.
