### ISSUE TITLE
LADV: Inkonsistenzen Enddaten

### ISSUE THREAD

**Issue by diwaffm** [leichtathletik/dlv-datenaustausch#50]
Bei den von LADV übermittelten Lizenzdaten ist das Enddatum der Athletenlizenz offen.
Das ist - soweit der Athlet nicht wechselt - auch korrekt.

Nicht dazu passt, dass die Mitgliedschaft aller Stammvereine zu einer LG zum 31.12. des laufenden Jahres endet.

So entsteht die Situation, dass ein Athlet ein Startrecht für eine LG auch für einem Zeitraum hat, in dem sein Stammverein nicht (mehr) Mitglied der LG ist.

Hier müsste konsequenterweise auch das Startrecht des Athleten zum 31.12. enden.

**Comment by mschunk** [comment]
Die Ermittlung des Startrecht Ende Datums wurde überarbeitet. Das update ist seit Ende letzter Woche live.
