### ISSUE TITLE
ca. 300 neue Vereine

### ISSUE THREAD

**Issue by mschunk** [leichtathletik/dlv-datenaustausch#52]
Datenabruf: 01.12.2019
Datenmodus: full
Landesverband: Würrtemberg 

Die Importvorschau der Daten aus Würrtemberg zeigt ca. 300 neue Vereine gegenüber dem letzten Stand aus Oktober:
```
2316: Sportverein Unterweissach 193, Zusätzlicher Name: SV Unterweissach
5357: Turnverein Gräfenhausen, Zusätzlicher Name: TV Gräfenhausen
2112: TV Kornwestheim, Zusätzlicher Name: TV Kornwestheim
6125: TV Sulgen, Zusätzlicher Name: TV Sulgen
1724: TSV Kupferzell, Zusätzlicher Name: TSV Kupferzell
4151: Sportverein Sillenbuch, Zusätzlicher Name: SV Sillenbuch
```

**Comment by santwer** [comment]
Hierbei handelte es sich um "Nichtmitglieder" diese werden nun genauer gefiltert.

**Comment by mschunk** [comment]
Datenabruf am 5.12.2019 - PRoblem nicht mehr vorhanden.
