### ISSUE TITLE
Abgeschnittene Vereinsnamen

### ISSUE THREAD

**Issue by mschunk** [leichtathletik/dlv-datenaustausch#53]
Datenabruf: 01.12.2019
Datenmodus: full
Landesverband: Würrtemberg 

Die Importvorschau zeigt eine ganze Reiehe von Vereinen bei denen der Vereinsname abgeschnitten wird. Beispiel:
```xml
<Club ID="WÜ0003570" CountyID="WÜ0000035" StateID="WÜ" Type="Club" Name="Polizeisportgemeinschaft Aale" City="Aalen" ShortName="Polizei SG Aalen" ...>
```

Neu laut XML:
Name: Polizeisportgemeinschaft Aale **(letzter Buchstabe fehlt)**
Kurzname: Polizei SG Aalen

Vereinsname bisher (COSA SPV):
Name: Polizeisportgemeinschaft Aalen
Kurzname: Polizei SG Aalen

Siehe: https://ladv.de/verein/namedetail/1025

**Comment by santwer** [comment]
Vereinsnamen werden nun im komplett mitgegeben, sie werden erst gekürzt, wenn der Vereinsname länger als 200 Zeichen ist. XSD.

**Comment by mschunk** [comment]
Datenabruf am 5.12.2019 - Problem nicht mehr vorhanden.
