### ISSUE TITLE
8600+ neue Athleten

### ISSUE THREAD

**Issue by mschunk** [leichtathletik/dlv-datenaustausch#54]
Datenabruf: 01.12.2019
Datenmodus: full
Landesverband: Würrtemberg

Die Importvorschau der Daten aus Würrtemberg zeigt 8600+ neue Athleten gegenüber dem letzten Stand aus Oktober.

Beispiel:
```xml
    <Person PersonID="60673688-2FED-4421-B4DF-DF04B91E95B8" FirstName="Niklas" LastName="Eff." ...>
      <Licenses>
        <License LicenseNumber="WÜ0024965" LicenseClubID="WÜ0004122" LicenseStart="2001-01-01" HomeClubID="WÜ0004122" LastUpdated="2014-02-11 22:02:24">
        </License>
      </Licenses>
    </Person>
```
8600 weitere neue Athleten

**Comment by santwer** [comment]
Dieses Thema ist nun nicht mehr relevant, da diese Athleten, nicht mehr im Abruf so mitgeführt werden.

**Comment by mschunk** [comment]
Datenabruf am 5.12.2019 - Athleten tauchen nicht mehr auf.
