### ISSUE TITLE
LADV -> LANet2: Daten aus Brandenburg: Vereine haben alle EINEN Bezirk- aber der wird nicht mitgeliefert

### ISSUE THREAD

**Issue by diwaffm** [leichtathletik/dlv-datenaustausch#55]
Die Vereine aus Brandenburg kommen alle mit dem selben Bezirk - dieser Bezirk wird aber nicht mit übertragen.

Wahrscheinlich ein Fehler in den Daten?

&lt;Club ID="BB0073078" CountyID="BB0000099" StateID="BB" Type="Club" Name="SV Alemania 52 Templin" City="Templin" ShortName="SV Alemania 52 Templin" ClubDateStart="2019-12-04" ClubDateEnd="2019-12-04" LastUpdated="2019-06-17 08:56:41"&gt;

**Comment by mschunk** [comment]
Vereinsdaten aus Brandenburg werden von Phönix bereitgestellt:
```xml
<StateData>
  <Request>
    <Mastersystem>Phoenix II</Mastersystem>
    <Created>2019-12-04 02:00:08</Created>
    <DateCUStart>2019-01-01</DateCUStart>
    <DateCUEnd>2020-01-02</DateCUEnd>
    <Mode>full</Mode>
  </Request>
```

LADV kann zum Inhalt der Daten keine Aussage machen.

**Comment by diwaffm** [comment]
D.h. Du hast Die Daten ungeprüft nach LADV übernommen und reichst sie so weiter?
Der Vereinsimport hätte dann ja schon beim Weg Phoenix -> LADV scheitern müssen...

**Comment by santwer** [comment]
Wie heute schon per Email bestätigt, werden alle Counties und Districts nun geprüft, ob sie im export enthalten sind. Falls nicht, wird beim Verein kein County oder District übernommen.

Außerdem gab es eine Anpassung in Baden nach Udo Laub.
> In Baden soll alles unter „district“ (Kreis) aufgelistet sein. In der Beschreibung sollte dann der komplette Name stehen: Kreis Bruchsal, Rhein-Neckar Kreis, Bezirk Oberrhein...
