### ISSUE TITLE
Württemberg: Inkonsistente Vereinsdaten

### ISSUE THREAD

**Issue by mschunk** [leichtathletik/dlv-datenaustausch#56]
Datenabruf: 05.12.2019
Datenmodus: full
Landesverband: Würrtemberg

Laut clubs.xml ist der **TSV Aach-Linz** Mitglied der LG Sigmaringen. Allerdings taucht der Verein nicht in den Clubs auf. Oder mit anderen Worten: ein nicht existierender Verein ist Mitglied der LG Sigmaringen. 

Erwartung: Ein Verein der Mitglied einer LG ist, wird auch in den Vereinen ausgegeben.

```xml
<Club ID="WÜ0007701" Type="LG" Name="LG Sigmaringen" ...>
      <MemberClubs>
        <MemberClub ID="WÜ0007732" Name="TSV Aach-Linz" MemberDateStart="2018-02-05" MemberAgeGroups="AKTIVEU20U18 U16U14"/>
```

**Comment by santwer** [comment]
Vereine die in SGs sind und als Nicht Mitglied, bzw. das Austrittsdatum aus dem Verband zu weit zurück liegt werden nicht mehr im export geliefert.

**Comment by mschunk** [comment]
Datenabruf am 10.12.2019 - Problem tritt nicht mehr auf.
