### ISSUE TITLE
Niedersachsen: Stgs als Club

### ISSUE THREAD

**Issue by mschunk** [leichtathletik/dlv-datenaustausch#58]
Datenabruf: 07.12.2019
Datenmodus: full
Landesverband: Niedersachsen

Probleme: 
- ` Type="Club"` sollte STG sein
- Vereine mit `ClubDateEnd="2018-12-31"` sollten nicht bereitgestellt werden

```xml
<Club ID="NI0003157" DistrictID="NI0000031" CountyID="NI0000003" StateID="NI" Type="Club" 
  Name="StG Hansa-Ettenbüttel" City="Hansa" ShortName="StG Hansa-Ettenbüttel" 
  ClubDateStart="2018-01-01" ClubDateEnd="2018-12-31" LastUpdated="2018-12-03 14:57:47">
  <MemberClubs>
  </MemberClubs>
</Club>
```

**Comment by santwer** [comment]
>  Type="Club" sollte STG sein

Das wurde von Niedersachen falsch eingetragen.
> Vereine mit ClubDateEnd="2018-12-31" sollten nicht bereitgestellt werden

Das ist nun geändert. Bei full wurde bislang daten ab 31.12 miteinbezogen, dass ist nun auf 1.1. geändert.

**Comment by mschunk** [comment]
Es gibt nun keine Vereine mehr mit `ClubDateEnd="2018-12-31"`
