### ISSUE TITLE
Brandenburg: Wer ist für was zuständig?

### ISSUE THREAD

**Issue by diwaffm** [leichtathletik/dlv-datenaustausch#59]
Ich habe von Marc den Api-Key zum Abruf der Daten aus Brandenburg bekommen.
Als Mastersystem für die Vereine ist im XML aber Phoenix hinterlegt.

Das Problem mit dem nicht existierenden Bezirk (https://github.com/leichtathletik/dlv-datenaustausch/issues/55) hat Sven auch lösen können.

Wenn ich nun die Personen abrufen möchte, bekomme ich eine Webseite (sic!), mit folgendem Inhalt:

500 - Fehler
Interner Anwendungsfehler
Der aktuelle Vorgang wurde aufgrund eines Problems abgebrochen und ein Fehlerprotokoll erstellt.
Vorschlag: Versuchen Sie die Aktion erneut. Tritt das Problem erneut auf, kontaktieren Sie uns per Email oder nutzen Sie unser Kontaktformular.

Wer ist hier nun zuständig?

**Comment by mschunk** [comment]
Der HTTP 500 wurde behoben.
