### ISSUE TITLE
Request Metadata

### ISSUE THREAD

**Issue by mschunk** [leichtathletik/dlv-datenaustausch#6]
Die Dateien enthalten:
```
<Request>
<Filename> </Filename>
<Version></Version>
<Created></Created>
<DateCUStart></DateCUStart>
<DateCUEnd></DateCUEnd>
</Request>
```
Die Felder sind in der Dokumentation nicht erklärt.
Dinge wie "Filename" erscheinen vollständig sinnlos bei einer Übertragung der daten per HTTP.

Was wichtig ist für die Datenübertragung:
1. Wann wurde die Datei erstellt
2. Welchen Datenstand enthält die Datei

**Comment by mschunk** [comment]
Folgende Felder sind nicht notwendig:
- Filename
- Version (über XSD Version gegeben)

Folgende Felder sollen erhalten bleiben:
- Created
- DateCUStart - Zeitraum
- DateCUEnd

Folgende Felder sollen aufgenommen werden:
- Mastersystem

**Comment by UdoLaubDLV** [comment]
In die Dokumentation so aufgenommen (vorläufig).

**Comment by mschunk** [comment]
Nachdem Vorschlag bzl. Datentransfer sollte in noch ein weiteres Element aufgenommen werden: `<Mode>` - Der Modus des Datentransfers. Mögliche Werte:
- `full` - es sind alle Daten für das aktuelle und das zukünftige Jahr vorhanden
- `delta` - es sind nur die Änderungen der letzten X-Tage enthalten.

Beispiel:
```xml
<Request>
  <Created></Created>
  <Mode>full</Mode>
</Request>
```

**Comment by UdoLaubDLV** [comment]
Sorry für die Frage: Muss dies so ins XSD mit Mode als simpleType?

Muss noch das Abrufbeispiel geändert werden?

**Comment by mschunk** [comment]
> Sorry für die Frage: Muss dies so ins XSD mit Mode als simpleType?

Ja

> Muss noch das Abrufbeispiel geändert werden?
Nein

**Comment by mschunk** [comment]
in Club.xsd vom 16.10.2019 umgesetzt.
