### ISSUE TITLE
Phönix: Startrechtwechsel unerwartetes Startrecht Ende Datum

### ISSUE THREAD

**Issue by mschunk** [leichtathletik/dlv-datenaustausch#60]
In den Athletendaten aus Phönix (LV Niedersachsen und LV Württemberg) gibt es sehr viele Startrechte die "irgendwann" im Oktober/November/Dezember Enden und dann ein neues Startrecht am 1.1.2020 beginnt. Vereinswechsel wärend der Wechselfrist. Bei Wechseln in der Wechselfrist ist es üblich das das Startrecht Ende der 31.12. ist, Landesverbände versuchen die Startrechtwechsel so zu erfassen (siehe Bild unten, `Letzter Wettkampf`). Es scheint so, als ob das Bearbietungsdatum als Endedatum für das Startrecht verwendet wird und es für den Landesverband keine Möglichkeit gibt das Ende Datum einer Startlizenz zu setzen oder dies nicht funktioniert.

Konkretes Beispiel anhand der Niedersachsen Daten:
```xml
<Person PersonID="13410589-D766-4336-9A3D-092D197E3D7B" FirstName="Frank" LastName="B." Gender="M" Yearofbirth="1969" ...  LastUpdated="2017-12-06 13:37:33">
      <Licenses>
        <License LicenseNumber="NI0000549" LicenseClubID="NI0002204" LicenseStart="2020-01-01" HomeClubID="NI0002204" LastUpdated="2019-12-02 10:45:43">
        </License>
        <License LicenseNumber="NI0000549" LicenseClubID="NI0002218" LicenseStart="2018-01-01" LicenseEnd="2019-12-01" HomeClubID="NI0002218" LastUpdated="2019-12-02 10:45:43">
        </License>
      </Licenses>
</Person>
```
--> LicenseEnd="2019-12-01"

Athlet in Phönix:
![grafik](https://user-images.githubusercontent.com/18612171/70546343-63ecbb00-1b6f-11ea-977d-0f75378dc033.png)

Landesverbände haben Versucht mit dem Datenfeld "Letzter Wettkampf" das Lizenzende Datum auf 31.12. zu setzen. Dies wird aber bei der generierung der XML anscheinend nicht verwendet.

Es ist unklar ob dies ein Ausgabeproblem der XML ist, ein Bedienungsproblem des Landesverbandes oder ...

**Comment by mschunk** [comment]
@santwer gibt es hier ein update?

**Comment by santwer** [comment]
Hier werden nun die Daten des letzten Wettkampfes, sofern eingetragen übermittelt.

**Comment by mschunk** [comment]
Test ist derzeit nicht möglich da wir keine XSD konformen Vereinsdaten bekommen - siehe:
https://github.com/leichtathletik/dlv-datenaustausch/issues/47

**Comment by santwer** [comment]
Da dies schon seit längerem behoben ist, bitte ich entweder noch weitere Infos zu den bestehenden Problem zu geben oder das Issue zu schließen.

**Comment by mschunk** [comment]
Problem tritt nicht mehr auf.
