### ISSUE TITLE
Phönix: Unterschiedlicher Jahrgang von Athleten in DLV XML und COSA SPV

### ISSUE THREAD

**Issue by mschunk** [leichtathletik/dlv-datenaustausch#62]
Bei den Tests der neuen XML Schnittstelle ist aufgefallen, das es eine geringe Anzahl an Athleten gibt bei denen sich der Jahrgang unterscheided, abhängig davon ob die Athletendaten in DLV XML oder in COSA SPV bereitgestellt werden.

DLV XML und COSA SPV wurden beide am 10.12. abgerufen.

Erwartung: Jahrgang von Athleten ist in beiden Datenformaten identisch.

Beispiele:
```xml
<Person PersonID="F5ABA236-7177-4741-ADD4-113FFB396F4D" FirstName="Albrecht" LastName="M." Yearofbirth="1966" ... />
<Person PersonID="C78619A5-C57C-4CED-91A2-17083F4B267C" FirstName="Jürgen" LastName="V." Yearofbirth="1958" ... />
```

Anzeige Athleten in COSA:
![Athlet1](https://user-images.githubusercontent.com/18612171/70655426-83134780-1c58-11ea-92a3-b8dfd47136da.png)
![Athlet2](https://user-images.githubusercontent.com/18612171/70655431-873f6500-1c58-11ea-9845-4bbd00519d41.png)

**Comment by santwer** [comment]
Dieses Problem wurde gelöst. Wir haben gestgestellt, dass der COSA Export innerhalb von Phoenix das Geburtsdatum der neueren Pässe nicht mehr richtig übernommen hat. Dies wurde angepasst, die COSA-Daten sind nun wie gepflegt übertragen.

**Comment by mschunk** [comment]
In den XML Daten die am 8.1.2020 2 Uhr erstellt wurden sehe ich die Unterschiede noch. Ich werde das morgen erneut prüfen.
