### ISSUE TITLE
Phönix: Bereitstellung Stammdaten LV Bremen

### ISSUE THREAD

**Issue by mschunk** [leichtathletik/dlv-datenaustausch#63]
Laut Auskunft des LV Bremen sind die Änderungen der Wechselfrist bearbeitet und die Stammdaten für 2020 können von LADV abgerufen werden. Der LV Bremen hat dazu folgende Information von Phönix erhalten:
> "Wir haben die DLV-Schnittstelle nun fertig gestellt, d.h. es können
> nun die Stammdaten der Vereine und die Startlizenzen zwischen den
> drei Systemen Phoenix II, LADV und LA.net2 regelmäßig
> (automatisiert, nächtlich) ausgetauscht werden.

Ein Datenabruf der Daten für Bremen ist nicht möglich:
```
curl -s -X GET -H "X-Auth-Token:<token>" "https://<host>/api/clubs?stateId=BR"
<?xml version="1.0" encoding="UTF-8"?>
<StateData>
  <Request>
    <Mastersystem>Phoenix II</Mastersystem>
    <Created>2019-12-14 18:27:08</Created>
    <DateCUStart>2019-12-14</DateCUStart>
    <DateCUEnd>2019-12-14</DateCUEnd>
    <Mode>delta</Mode>
  </Request>
  <Error>Mandant not found</Error>
</StateData>
```

**Comment by santwer** [comment]
Bremen ist nun auch bereit gestellt.

**Comment by mschunk** [comment]
Datenabruf war heute möglich.
