### ISSUE TITLE
Element Club Attribut Parent

### ISSUE THREAD

**Issue by mschunk** [leichtathletik/dlv-datenaustausch#7]
Laut Dokumentation enthält das Attribut Club ein Attribut "Parent". Es ist unklar was die "Eltern" eines Clubs sind. Eine Erklärung gibt es nicht.

**Comment by mschunk** [comment]
unbekannt was das ist - Feld wird entfernt.

**Comment by UdoLaubDLV** [comment]
In die Dokumentation so aufgenommen.
