### ISSUE TITLE
Seltec: Athlet gehört gleichzeitig zwei Vereinen an

### ISSUE THREAD

**Issue by mschunk** [leichtathletik/dlv-datenaustausch#70]
In den Thüringen Daten, abgerufen 19.12. gibt es Athleten die gleichzeitig mehrere gültige Startlizenzen für unterschiedliche Vereine haben. 

Beispiel:
```xml
<Person PersonID="c67d5bb9-fbfc-11e9-bde2-6c626d40fea8" FirstName="Sven" LastName="J." ...>
<Licenses>
<License LicenseNumber="TH0080480" HomeClubID="TH0000057" LicenseClubID="TH0000057" LicenseStart="2012-01-01" LicenseEnd="2019-04-30" LastUpdated="2019-04-29 14:36:45"/>
<License LicenseNumber="TH0080480" HomeClubID="TH0000255" LicenseClubID="TH0000255" LicenseStart="2019-05-01" LicenseEnd="2026-12-31" LastUpdated="2019-04-29 14:37:41"/>
</Licenses>
</Person>

<Person PersonID="c67d5bb9-fbfc-11e9-bde2-6c626d40fea8" FirstName="Sven" LastName="J." ...>
<Licenses>
<License LicenseNumber="TH0080480" HomeClubID="TH0000057" LicenseClubID="TH0000057" LicenseStart="2012-01-01" LicenseEnd="2019-04-30" LastUpdated="2019-04-29 14:36:45"/>
<License LicenseNumber="TH0080480" HomeClubID="TH0000255" LicenseClubID="TH0000255" LicenseStart="2019-05-01" LicenseEnd="2026-12-31" LastUpdated="2019-04-29 14:37:41"/>
</Licenses>
</Person>
```

Die `c79f97b5-fbfc-11e9-bde2-6c626d40fea8` sieht ähnlich aus.

**Comment by diwaffm** [comment]
Wo ist das Problem?

Wenn der Athlet für den alten Verein seit 9 Monaten nicht gestartet ist, kann er auch außerhalb der Wechselfrist ein Startrecht für einen neuen Verein bekommen...

**Comment by mschunk** [comment]
> Wo ist das Problem?

Das es für **eine** GUID **zwei** Person-Elemente gibt die sich jeweils in `ClubID` unterscheiden. Die Lizenzen sind auch doppelt, einmal pro Person-Element.

Erwartung:
- zu einer GUID gibt es ein Person-Element
- Lizenzen für einen Athleten werden nicht mehrfach ausgegeben

Siehe Beispiel oben.

**Comment by diwaffm** [comment]
Athleten, die den Verein wechseln, werden jetzt nur noch einmal gelistet.

**Comment by mschunk** [comment]
passt nun
