### ISSUE TITLE
Seltec: Gemeinschaften 2020 / Athleten 2020 fehlen

### ISSUE THREAD

**Issue by mschunk** [leichtathletik/dlv-datenaustausch#71]
In den Vereinsdaten gibt es keine einzige Gemeinschaft mit `MemberDateStart="2020-01-01"`. Die Gemeinschtsliste 2020 Thüringen liegt mir bereits vor und es gibt einige Änderungen bei den STGs die in der XML offenbar fehlen.

Desweiteren ist es sehr auffällig, dass es bei den Athleten keine einzige Lizenz gibt mit `LicenseStart="2020-01-01"`. Bitte prüfen.

**Comment by diwaffm** [comment]
Der Export erfolgte nur für das laufende Jahr...
Ist korrigiert.

**Comment by mschunk** [comment]
Nun gibt es Athleten und Gemeinschaften für 2020:
```
LicenseStart="2020-01-01" ... 136
MemberDateStart="2020-01-01" ... 29
```
