### ISSUE TITLE
Seltec: HTTP 500 bei Abfrage Daten Thüringen

### ISSUE THREAD

**Issue by mschunk** [leichtathletik/dlv-datenaustausch#73]
Bei Abfrage der Daten aus Thüringen, full mode, clubs, wird die Anfrage wieder mit `HTTP 500: Interner Server Fehler` beantwortet.

**Comment by diwaffm** [comment]
sollte wieder gehen...

**Comment by mschunk** [comment]
Funktioniert nun wieder.
