### ISSUE TITLE
Seltec: Athleten fehlen

### ISSUE THREAD

**Issue by mschunk** [leichtathletik/dlv-datenaustausch#75]
Datenabruf am 1.1.2020, ca. 18:30 Uhr; Datenmodus full.

Der LV Thüringen berichtet, dass Athleten fehlen. Beispiel: 107719 Helena Broßmann TSV Germania Neustadt/O.

Die Athletin ist in der athleten.xml nicht vorhanden. In ATL.CSV ist die Athletin vorhanden.

**Comment by mschunk** [comment]
Weitere untersuchungen zeigen, dass 20 weitere Athleten betroffen sind. Diese werden über ATL.CSV bereitgestellt, sind in der Athleten-XML aber nicht vorhanden. Weitere Beispiele:
```
107733: Enya G., W, 2008, GER
107732: Oskar B., M, 2006, GER
107731: Jette E., W, 2008, GER
106447: Tim-Christopher S., M, 2000, GER
107730: Fabian G., M, 2004, GER
```

Es gibt allerdings auch den Umgekehrten Fall. Athleten die in Athleten-XML vorhanden sind, nicht im ATL.CSV. Beispiele (insgesamt sind es 25):
```
24000: Utz D., M, 1934, GER
44390: Gerd H., M, 1956, GER
52710: Uwe Z., M, 1955, GER
82270: Diana S., W, 1975, GER
82390: Ramona H., W, 1975, GER 
```

**Comment by diwaffm** [comment]
Die CSV-Dateien wurden **nach** den XML-Dateien erstellt, von daher die Unterschiede.
Am Server liegen jetzt heute erstellte Versionen der Dateien...

Wenn die Dateien prinzipiell OK sind, werde ich eine Automatik einrichten, die die FULL-Dateien jede Nacht neu erstellt...

**Comment by mschunk** [comment]
Grundsätzlich sehen die Daten gut aus. Allerdings werden wir mit dem regelmässigen Import erst beginnen wenn die Daten von den Landesverbänden freigegeben wurden. Ohne aktuelle Daten ist dies nicht möglich.

Uns wäre es am liebsten wenn die Daten live zur Verfügung gestellt werden, so wie LADV dies tut.

**Comment by mschunk** [comment]
Die Daten aus Thüringen sind jetzt aktuell: `2020-01-02 19:40:14` und sehen gut aus.

Die Daten aus Hamburg sind weiterhin nicht aktuell: `2019-12-23 17:32:34`

Die Daten aus Westfalen sind weiterhin nicht XSD konform. Siehe: https://github.com/leichtathletik/dlv-datenaustausch/issues/76

**Comment by diwaffm** [comment]
Ja, ich bezog mich ausschließlich auf Thüringen, da es hier im Issue um diesen LV ging...
Sowohl für Hamburg als auch für Westfalen warte ich noch auf Rückmeldungen...

**Comment by mschunk** [comment]
Der LV Thüringen hat bestätigt das die Daten ok sind. LADV ist bereit für den täglichen abruf.

**Comment by mschunk** [comment]
Der tägliche Abruf für TH ist seit heute aktiv.
