### ISSUE TITLE
Seltec: Athlete XML ist nicht XSD konform

### ISSUE THREAD

**Issue by mschunk** [leichtathletik/dlv-datenaustausch#76]
Landesverband: Westfalen,
Datenabruf: 1.1.2020, ca. 19:40 Uhr
Datenmodus: full

Die Validierung der XML Datei gegen das Schema schlägt fehl:
`cvc-complex-type.4: Attribut 'LicenseStart' muss in Element 'License' vorkommen.`

**Comment by diwaffm** [comment]
Das Problem ist behoben, Westfalen steht zum Abruf bereit...

**Comment by mschunk** [comment]
Datenabruf am 4.1.2020  - Problem tritt nicht mehr auf.
