### ISSUE TITLE
Element Club, Attribute IsLG und IsSTG

### ISSUE THREAD

**Issue by mschunk** [leichtathletik/dlv-datenaustausch#8]
Unübliche und umständliche Verwendung von XML. 

Üblicher wäre ein Attribute `type` das ein Enum ist mit den Werten `Club|LG|STG`.

**Comment by mschunk** [comment]
Alle Anwesenden einverstanden.

**Comment by UdoLaubDLV** [comment]
In die Dokumentation und XSD so aufgenommen.

**Comment by mschunk** [comment]
Ist umgesetzt
