### ISSUE TITLE
Nordrhein: HTTP 500 Interner Server Fehler

### ISSUE THREAD

**Issue by mschunk** [leichtathletik/dlv-datenaustausch#87]
Abfrage der Athletendaten aus Nordrhein liefert HTTP 500 - Interner Serverfehler.

**Comment by diwaffm** [comment]
Fehler 500 kommt nicht mehr...

**Comment by mschunk** [comment]
Datenabruf am 29.01.2019 - Problem ist nicht mehr vorhanden.
