### ISSUE TITLE
Westfalen: Athleten gehören nicht existierendem Verein an

### ISSUE THREAD

**Issue by mschunk** [leichtathletik/dlv-datenaustausch#89]
Datenabruf 3.2.2020
Datenmode: full

Beispiele:
```xml
<Person PersonID="c527e7ea-fbfc-11e9-bde2-6c626d40fea8" FirstName="Franz" LastName="B."  ClubID="WE0002705" ...>
<Person PersonID="c527e943-fbfc-11e9-bde2-6c626d40fea8" FirstName="Thomas" LastName="B." ClubID="WE0002705" ...>
```
Weitere Athleten...

Die Athleten gehören dem Verein `WE0002705` an, der in CLUBS.XML nicht existiert. Athleten die einem, nicht existierenden Verein angehören.

**Comment by thilopohl** [comment]
Hallo zusammen. 

Inhaltlich scheint das ganze gefixt zu sein. (Athleten aus fehlendem Verein - Lizenzen wurden manuell beendet.)

Dennoch weigert sich LADV beharrlich, den Verein WE 2705 zu löschen. 

2705: ETuS Haltern [Daten vorhanden, Verein weiterhin vorhanden]

In den mir zur Verfügung stehenden XML-Dateien für Westfalen finde ich weder Angaben zu einem Verein 2705, noch verweist irgendeine AthletenLizent auf den Verein 2705.


Ciao Thilo

**Comment by mschunk** [comment]
> Dennoch weigert sich LADV beharrlich, den Verein WE 2705 zu löschen.
fixed
