### ISSUE TITLE
Clubs/MemberClubs/AgeGroups

### ISSUE THREAD

**Issue by mschunk** [leichtathletik/dlv-datenaustausch#9]
Exterem umständliche Abbildung von Mitgliedschaften einer Gemeinschaft. Kann deutlich vereinfacht werden. Siehe http://html.ladv.de/api/2016-01-24-LADV-Stammdaten-Datenformat.pdf

**Comment by mschunk** [comment]
Vorschlag vereinfachen:
```
<Club ID="" ClubCode="" Name=" " MemberDateStart="" MemberDateEnd="" aliance="U16U14"/>
```
und Element `AgeGroup` entfernen.

**Comment by mschunk** [comment]
Alle Anwesenden einverstanden.

**Comment by UdoLaubDLV** [comment]
In die Dokumentation so aufgenommen.
