### ISSUE TITLE
Pfalz: mehrfach vergebene Vereinsnummern

### ISSUE THREAD

**Issue by mschunk** [leichtathletik/dlv-datenaustausch#91]
Es gibt Vereinsnummern die mehrfach vergeben sind: 1000000, 602

**Comment by mschunk** [comment]
Datenabruf am 3.3.2020 - es sind weiterhin Vereinsnummern doppelt vergeben.

**Comment by diwaffm** [comment]
Ja
Ich habe den LV informiert und bislang noch keine Rückmeldung erhalten...

**Comment by mschunk** [comment]
Datenabruf am 14.05.2020 - es sind weiterhin die doppelten Vereinsnummern vorhanden: `1000000`, `602`.

**Comment by diwaffm** [comment]
Der LV-Pfalz sagt, die doppelten Dateinummern seien korrigiert.
Im Export sind keine Doubletten mehr zu sehen...

**Comment by mschunk** [comment]
Datenabruf 01.06.2020 - Problem ist behoben-
