### ISSUE TITLE
Nordrhein: Gemeinschaft ohne Mitglieder

### ISSUE THREAD

**Issue by mschunk** [leichtathletik/dlv-datenaustausch#93]
NO0020166: LAV Bayer Uerd./Dormagen

**Comment by diwaffm** [comment]
Es gib nun nur noch die 20165: LAV Bayer Uerdingen/Dormargen
20166 wurde beendet.

**Comment by mschunk** [comment]
Datenabruf am 3.3.2020 - keine Gemeinschaften ohne Mitglieder mehr
