### ISSUE TITLE
Nordrhein: Athleten mit mehreren gültige überlappende Lizenzen

### ISSUE THREAD

**Issue by mschunk** [leichtathletik/dlv-datenaustausch#94]
Datenabruf am 3.3.2020.

Datenabruf enthält Athleten mit mehreren gültige überlappende Lizenzen. Beispiele:
```
c3565253-fbfc-11e9-bde2-6c626d40fea8
c43910c8-fbfc-11e9-bde2-6c626d40fea8
```

**Comment by diwaffm** [comment]
Warum fällt das erst jetzt auf?
Für beide Personen sollten die überlappenden Lizenzen sollten schon beim allerersten Abruf in der Datei enthalten gewesen sein.

In der aktuellen Datei sollten sie aber nicht mehr enthalten sein...

**Comment by mschunk** [comment]
Datenabruf am 5.3. - Problem tritt nicht mehr auf.
