### ISSUE TITLE
Phönix: sehr viele gelöschte Athleten in Hessen/Niedsachsen/Sachsen/Württemberg

### ISSUE THREAD

**Issue by mschunk** [leichtathletik/dlv-datenaustausch#95]
Datenabruf: 15.04.2020
Datenmodus: full

Im Datenabgleich heute Nacht werden für die Landesverbände Hessen/Niedsachsen/Sachsen/Württemberg deutlich weniger Athleten bereitgestellt. Rückfrage bei den Landesverbänden hat ergeben, dass keine Löschungen in diesem Umfang stattgefunden haben. Es liegt offentsichtlich ein Fehler in der Datenbereitstellung for.

Württemberg: 5074 entfernte Athleten
Sachsen: 3067 entfernte Athleten
Niedersachsen: 6698 entfernte Athleten
Hessen: 8277 entfernte Athleten

**Comment by santwer** [comment]
Durch ein großes Update auf eine neue Version von PHP kam es hier zu Änderungen.
Ich habe mir das angeschaut und gefixt. Es ist nun so angepasst, dass bei weiteren Updates des Servers keine Fehler sich hier mehr einschleichen sollten.
Der Abruf ab 15.04.2020 13:30 ist korrigiert.

**Comment by mschunk** [comment]
Die letzten zwei Tage hat der Datenableich wieder ohne 10.000+ "gelöschte" Athleten funktioniert.
